import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../app/theme/app_typography.dart';
import '../../app/theme/design_tokens.dart';
import '../../flutter_flow/custom_icons.dart';
import '../../shared/widgets/wpcc_shimmer.dart';
import '../wisdom/wisdom_devotional_feature.dart' show WisdomFeatureTopBar;

class PrayerAlert {
  const PrayerAlert({required this.id, required this.label, required this.time, required this.days, this.durationMinutes, this.sound = '', this.vibration = true, this.snooze = true, this.enabled = true});
  final String id; final String label; final TimeOfDay time; final Set<int> days; final int? durationMinutes; final String sound; final bool vibration; final bool snooze; final bool enabled;
  PrayerAlert copyWith({String? label, TimeOfDay? time, Set<int>? days, int? durationMinutes, bool clearDuration = false, String? sound, bool? vibration, bool? snooze, bool? enabled}) => PrayerAlert(id: id, label: label ?? this.label, time: time ?? this.time, days: days ?? this.days, durationMinutes: clearDuration ? null : durationMinutes ?? this.durationMinutes, sound: sound ?? this.sound, vibration: vibration ?? this.vibration, snooze: snooze ?? this.snooze, enabled: enabled ?? this.enabled);
  Map<String, Object?> toJson() => {'id': id, 'label': label, 'hour': time.hour, 'minute': time.minute, 'days': days.toList(), 'duration': durationMinutes, 'sound': sound, 'vibration': vibration, 'snooze': snooze, 'enabled': enabled};
  factory PrayerAlert.fromJson(Map<String, dynamic> json) => PrayerAlert(id: json['id']?.toString() ?? DateTime.now().microsecondsSinceEpoch.toString(), label: json['label']?.toString() ?? 'Prayer', time: TimeOfDay(hour: json['hour'] as int? ?? 6, minute: json['minute'] as int? ?? 0), days: (json['days'] as List? ?? const []).whereType<int>().toSet(), durationMinutes: json['duration'] as int?, sound: json['sound']?.toString() ?? '', vibration: json['vibration'] != false, snooze: json['snooze'] != false, enabled: json['enabled'] != false);
}

class PrayerAlertStore {
  static const _key = 'wpcc_v76_personal_prayer_alerts';
  Future<List<PrayerAlert>> load() async { final preferences = await SharedPreferences.getInstance(); final raw = preferences.getString(_key); if (raw == null) return const []; final decoded = jsonDecode(raw) as List; return decoded.whereType<Map>().map((item) => PrayerAlert.fromJson(Map<String, dynamic>.from(item))).toList(growable: false); }
  Future<void> save(List<PrayerAlert> alerts) async { final preferences = await SharedPreferences.getInstance(); await preferences.setString(_key, jsonEncode(alerts.map((alert) => alert.toJson()).toList())); }
}

class PrayerAlertsScreen extends StatefulWidget { const PrayerAlertsScreen({super.key, this.onEdit}); final ValueChanged<PrayerAlert?>? onEdit; @override State<PrayerAlertsScreen> createState() => _PrayerAlertsScreenState(); }
class _PrayerAlertsScreenState extends State<PrayerAlertsScreen> { final _store = PrayerAlertStore(); late Future<List<PrayerAlert>> _future; @override void initState() { super.initState(); _future = _store.load(); } void _reload() => setState(() => _future = _store.load()); Future<void> _toggle(List<PrayerAlert> alerts, PrayerAlert alert, bool enabled) async { final updated = alerts.map((item) => item.id == alert.id ? item.copyWith(enabled: enabled) : item).toList(); await _store.save(updated); _reload(); }
 @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: FutureBuilder<List<PrayerAlert>>(future: _future, builder: (context, snapshot) { if (snapshot.connectionState != ConnectionState.done) return const WpccScreenShimmer(); if (snapshot.hasError) return _PrayerMessage(title: 'Prayer alerts unavailable', message: 'Your personal alerts could not be loaded.', onRetry: _reload); final alerts = snapshot.data ?? const []; return ListView(padding: const EdgeInsets.fromLTRB(20, 16, 20, 112), children: [const WisdomFeatureTopBar(title: 'Prayer alerts'), const SizedBox(height: 20), Text('Prayer alerts', style: context.appText.pageName()), const SizedBox(height: 6), Text('Prayer reminders and church-wide prayer alerts.', style: context.appText.supportText()), const SizedBox(height: 30), Row(children: [Text('Church prayer alerts', style: context.appText.sectionTitle()), const Spacer(), Text('Admin managed', style: context.appText.metadataText())]), const SizedBox(height: 10), const _GlobalAlertCard(), const SizedBox(height: 22), Row(children: [Text('My prayer alerts', style: context.appText.sectionTitle()), const Spacer(), TextButton(onPressed: () => widget.onEdit?.call(null), child: const Text('Add'))]), const SizedBox(height: 2), if (alerts.isEmpty) _PersonalEmpty(onCreate: () => widget.onEdit?.call(null)) else _PersonalAlertList(alerts: alerts, onToggle: (alert, enabled) => _toggle(alerts, alert, enabled), onEdit: widget.onEdit), const SizedBox(height: 18), Text('Personal alerts stay on this device until a church calendar or push scheduling service is connected.', style: context.appText.compactCaption())]; })))); }

class PrayerAlertEditScreen extends StatefulWidget { const PrayerAlertEditScreen({super.key, this.initialAlert, required this.onSave}); final PrayerAlert? initialAlert; final ValueChanged<PrayerAlert> onSave; @override State<PrayerAlertEditScreen> createState() => _PrayerAlertEditScreenState(); }
class _PrayerAlertEditScreenState extends State<PrayerAlertEditScreen> { late final TextEditingController _label; late final TextEditingController _duration; late TimeOfDay _time; late Set<int> _days; late bool _vibration; late bool _snooze; @override void initState() { super.initState(); final item = widget.initialAlert; _label = TextEditingController(text: item?.label ?? 'Prayer Alarm'); _duration = TextEditingController(text: item?.durationMinutes?.toString() ?? ''); _time = item?.time ?? const TimeOfDay(hour: 6, minute: 0); _days = item?.days ?? {1,2,3,4,5}; _vibration = item?.vibration ?? true; _snooze = item?.snooze ?? true; } @override void dispose() { _label.dispose(); _duration.dispose(); super.dispose(); }
 Future<void> _pickTime() async { final value = await showTimePicker(context: context, initialTime: _time); if (value != null) setState(() => _time = value); } void _save() { final label = _label.text.trim(); if (label.isEmpty || _days.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Add a label and at least one repeat day.'))); return; } final duration = int.tryParse(_duration.text.trim()); widget.onSave(PrayerAlert(id: widget.initialAlert?.id ?? DateTime.now().microsecondsSinceEpoch.toString(), label: label, time: _time, days: _days, durationMinutes: duration, vibration: _vibration, snooze: _snooze)); Navigator.of(context).maybePop(); }
 @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(20, 16, 20, 36), children: [WisdomFeatureTopBar(title: widget.initialAlert == null ? 'New Prayer Alert' : 'Edit Prayer Alert', onBack: () => Navigator.of(context).maybePop()), const SizedBox(height: 26), Center(child: Text(_time.format(context), style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontSize: 44))), const SizedBox(height: 28), _EditorCard(children: [_InputRow(label: 'Label', hint: 'Name this alarm', controller: _label), _EditorSection(title: 'Repeat', subtitle: 'Select the days for this alarm', child: Wrap(spacing: 8, children: List.generate(7, (index) { final selected = _days.contains(index); const labels = ['S','M','T','W','T','F','S']; return ChoiceChip(label: Text(labels[index]), selected: selected, onSelected: (_) => setState(() => selected ? _days.remove(index) : _days.add(index)), selectedColor: const Color(0xFF141419), labelStyle: TextStyle(color: selected ? Colors.white : context.tokens.textPrimary)); }))), _EditorSection(title: 'Duration', subtitle: 'Optional. Leave empty to count up', child: TextField(controller: _duration, keyboardType: TextInputType.number, decoration: const InputDecoration(hintText: 'None', suffixText: 'minutes'))), _EditorSection(title: 'Time', subtitle: _time.format(context), child: TextButton(onPressed: _pickTime, child: const Text('Change time'))), SwitchListTile(contentPadding: EdgeInsets.zero, title: Text('Vibration', style: context.appText.cardTitleSans()), subtitle: Text('Vibrate when the alert rings', style: context.appText.supportText()), value: _vibration, onChanged: (value) => setState(() => _vibration = value)), SwitchListTile(contentPadding: EdgeInsets.zero, title: Text('Snooze', style: context.appText.cardTitleSans()), subtitle: Text('Allow a 5-minute snooze', style: context.appText.supportText()), value: _snooze, onChanged: (value) => setState(() => _snooze = value))]), const SizedBox(height: 14), FilledButton(onPressed: _save, child: const Text('Save prayer alert'))])));
}

class PrayerSessionScreen extends StatefulWidget { const PrayerSessionScreen({super.key, required this.alert, this.playlist = const ['Morning Worship', 'Intercession Piano', 'Scripture Strings', 'Night Prayer']}); final PrayerAlert alert; final List<String> playlist; @override State<PrayerSessionScreen> createState() => _PrayerSessionScreenState(); }
 class _PrayerSessionScreenState extends State<PrayerSessionScreen> with WidgetsBindingObserver { Timer? _timer; Duration _elapsed = Duration.zero; bool _paused = false; int? _activeTrack; @override void initState() { super.initState(); WidgetsBinding.instance.addObserver(this); _timer = Timer.periodic(const Duration(seconds: 1), (_) { if (!_paused && mounted) setState(() => _elapsed += const Duration(seconds: 1)); }); } @override void didChangeAppLifecycleState(AppLifecycleState state) { if (state != AppLifecycleState.resumed) setState(() => _paused = true); } @override void dispose() { WidgetsBinding.instance.removeObserver(this); _timer?.cancel(); super.dispose(); } Duration get _display => widget.alert.durationMinutes == null ? _elapsed : (Duration(minutes: widget.alert.durationMinutes!) - _elapsed).isNegative ? Duration.zero : Duration(minutes: widget.alert.durationMinutes!) - _elapsed; String get _clock => '${_display.inMinutes.remainder(60).toString().padLeft(2, '0')}:${_display.inSeconds.remainder(60).toString().padLeft(2, '0')}'; @override Widget build(BuildContext context) { final duration = widget.alert.durationMinutes; final progress = duration == null ? 0.0 : (_elapsed.inSeconds / Duration(minutes: duration).inSeconds).clamp(0.0, 1.0); return Scaffold(body: SafeArea(child: Column(children: [WisdomFeatureTopBar(title: widget.alert.label, onBack: () => Navigator.of(context).maybePop()), const SizedBox(height: 28), Stack(alignment: Alignment.center, children: [SizedBox(width: 226, height: 226, child: CircularProgressIndicator(value: duration == null ? null : progress, strokeWidth: 16, color: const Color(0xFFBCA9ED), backgroundColor: const Color(0xFFE9E7F3))), Column(children: [Text(_clock, style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontSize: 44)), const SizedBox(height: 4), Text(duration == null ? 'Prayer time' : 'Countdown · ${duration} min', style: context.appText.metadataText())])]), const SizedBox(height: 26), Expanded(child: ListView.builder(padding: const EdgeInsets.fromLTRB(20, 0, 20, 24), itemCount: widget.playlist.length, itemBuilder: (context, index) => _PlaylistCard(title: widget.playlist[index], active: _activeTrack == index, onTap: () => setState(() => _activeTrack = _activeTrack == index ? null : index)))), Padding(padding: const EdgeInsets.fromLTRB(20, 0, 20, 22), child: FilledButton.icon(onPressed: () => setState(() => _paused = !_paused), icon: Icon(_paused ? FFIcons.kplay : FFIcons.kpause), label: Text(_paused ? 'Resume' : 'Pause')))]))); }
}

class _GlobalAlertCard extends StatelessWidget { const _GlobalAlertCard(); @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: context.tokens.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: context.tokens.border)), child: Row(children: [const Icon(FFIcons.kbell, size: 24), const SizedBox(width: 12), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('5:30 AM', style: TextStyle(fontSize: 30, height: 1)), SizedBox(height: 4), Text('Morning Prayer'), SizedBox(height: 3), Text('Every day · Morning Worship', style: TextStyle(fontSize: 12, color: Color(0xFF8A8795))) ])), Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6), decoration: BoxDecoration(color: const Color(0xFFEFE7F8), borderRadius: BorderRadius.circular(14)), child: const Text('Global', style: TextStyle(color: Color(0xFF6D3999), fontSize: 11)))])); }
class _PersonalAlertList extends StatelessWidget { const _PersonalAlertList({required this.alerts, required this.onToggle, this.onEdit}); final List<PrayerAlert> alerts; final void Function(PrayerAlert, bool) onToggle; final ValueChanged<PrayerAlert?>? onEdit; @override Widget build(BuildContext context) => Container(decoration: BoxDecoration(color: context.tokens.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: context.tokens.border)), child: Column(children: alerts.map((alert) => ListTile(onTap: () => onEdit?.call(alert), title: Text(alert.time.format(context), style: const TextStyle(fontSize: 31, height: 1)), subtitle: Text('${alert.label}\n${_dayText(alert.days)} · ${alert.durationMinutes == null ? 'Count up' : '${alert.durationMinutes} min'}', style: context.appText.supportText()), isThreeLine: true, trailing: Switch(value: alert.enabled, onChanged: (value) => onToggle(alert, value))).toList(growable: false))); } String _dayText(Set<int> days) => days.length == 7 ? 'Every day' : days.length == 5 && !days.contains(0) && !days.contains(6) ? 'Weekdays' : 'Custom days'; }
class _PersonalEmpty extends StatelessWidget { const _PersonalEmpty({required this.onCreate}); final VoidCallback onCreate; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: context.tokens.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: context.tokens.border)), child: Column(children: [Text('No personal prayer alerts', style: context.appText.cardTitleStrong()), const SizedBox(height: 6), Text('Create one for your regular prayer time.', textAlign: TextAlign.center, style: context.appText.supportText()), TextButton.icon(onPressed: onCreate, icon: const Icon(FFIcons.kplus), label: const Text('Create alert'))])); }
class _EditorCard extends StatelessWidget { const _EditorCard({required this.children}); final List<Widget> children; @override Widget build(BuildContext context) => Container(decoration: BoxDecoration(color: context.tokens.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: context.tokens.border)), child: Column(children: children)); }
class _InputRow extends StatelessWidget { const _InputRow({required this.label, required this.hint, required this.controller}); final String label; final String hint; final TextEditingController controller; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.all(14), child: TextField(controller: controller, decoration: InputDecoration(labelText: label, hintText: hint, border: InputBorder.none))); }
class _EditorSection extends StatelessWidget { const _EditorSection({required this.title, required this.subtitle, required this.child}); final String title; final String subtitle; final Widget child; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(14), decoration: BoxDecoration(border: Border(top: BorderSide(color: context.tokens.border))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: context.appText.cardTitleSans()), Text(subtitle, style: context.appText.supportText()), const SizedBox(height: 9), child])); }
class _PlaylistCard extends StatelessWidget { const _PlaylistCard({required this.title, required this.active, required this.onTap}); final String title; final bool active; final VoidCallback onTap; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 12), child: Material(color: context.tokens.surface, borderRadius: BorderRadius.circular(22), child: InkWell(onTap: onTap, borderRadius: BorderRadius.circular(22), child: Container(height: 88, padding: const EdgeInsets.symmetric(horizontal: 20), decoration: BoxDecoration(borderRadius: BorderRadius.circular(22), border: Border.all(color: active ? const Color(0xFFD9C9F0) : context.tokens.border)), child: Row(children: [Expanded(child: Column(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: context.appText.cardTitleStrong()), const SizedBox(height: 4), Text(active ? 'Playing' : 'Prayer playlist', style: context.appText.supportText())])), CircleAvatar(backgroundColor: const Color(0xFF121218), child: Icon(active ? FFIcons.kpause : FFIcons.kplay, color: Colors.white, size: 18))]))))); }
class _PrayerMessage extends StatelessWidget { const _PrayerMessage({required this.title, required this.message, required this.onRetry}); final String title; final String message; final VoidCallback onRetry; @override Widget build(BuildContext context) => Center(child: Padding(padding: const EdgeInsets.all(28), child: Column(mainAxisSize: MainAxisSize.min, children: [const Icon(FFIcons.kbellSlash, size: 30), const SizedBox(height: 14), Text(title, style: context.appText.cardTitleStrong()), const SizedBox(height: 6), Text(message, textAlign: TextAlign.center, style: context.appText.supportText()), TextButton(onPressed: onRetry, child: const Text('Retry'))]))); }
