"use client";
import Link from "next/link";
import posthog from "posthog-js";
import type { PageData } from "./queries";
import { DashboardPagination } from "./dashboard-pagination";
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"AE";
const date=(value:string)=>{const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?"—":new Intl.DateTimeFormat("en-NG",{day:"2-digit",month:"short",year:"numeric"}).format(parsed);};
const label=(status:string)=>status==="completed"?"Finished":status==="yet_to_attend"?"Yet to attend":"Unfinished";
const capture=(id:string,target:string)=>{if(posthog.has_opted_in_capturing())posthog.capture("academy_enrolment_opened",{enrolment_id:id,target});};
export function AcademyEnrolmentsDirectory({data}:{data:PageData}){return <section className="directory-panel academy-enrolments-panel"><div className="panel-heading"><div><h2>Enrolment directory</h2><p>Member class assignments and learning progress.</p></div><span>{data.pagination?.total||0} enrolments</span></div>{data.rows.length?<><div className="table-scroll" tabIndex={0} aria-label="Scrollable academy enrolments"><table className="data-table academy-enrolments-table"><thead><tr><th scope="col">Member</th><th scope="col">Membership code</th><th scope="col">Class</th><th scope="col">Assignment source</th><th scope="col">Progress</th><th scope="col">Last activity</th><th scope="col">Status</th></tr></thead><tbody>{data.rows.map(row=>{const progress=Math.max(0,Math.min(100,Number(row.details?.progress_percent||0)));return <tr key={row.id}><td><Link href={`/dashboard/members?q=${encodeURIComponent(row.secondary)}`} onClick={()=>capture(row.id,"member")}><div className="identity-cell"><div className="initials">{initials(row.primary)}</div><div><strong>{row.primary}</strong><span>{row.secondary}</span></div></div></Link></td><td>{row.details?.membership_code||"—"}</td><td><Link className="academy-class-link" href={`/dashboard/academy/classes?selected=${encodeURIComponent(row.details?.course_id||"")}`} onClick={()=>capture(row.id,"class")}><strong>{row.details?.class_name||"Class"}</strong><small>{row.details?.class_code||"No code"}</small></Link></td><td>{row.details?.assignment_source||"Direct"}</td><td><div className="progress-cell"><span>{progress}%</span><progress max="100" value={progress} aria-label={`${row.primary} learning progress`}>{progress}%</progress></div></td><td>{date(row.details?.updated_at||row.details?.created_at||"")}</td><td><span className={`status-pill status-${row.status.replaceAll("_","-")}`}>{label(row.status)}</span></td></tr>;})}</tbody></table></div>{data.pagination&&<DashboardPagination {...data.pagination} label="Academy enrolment pages"/>}</>:<div className="empty-state"><h3>No enrolments found</h3><p>No enrolments match the current authorised filters.</p></div>}</section>;}
