"use client";

import * as Sentry from "@sentry/nextjs";
import { DownloadSimpleIcon, FileIcon, XIcon } from "@phosphor-icons/react";
import { useEffect, useRef, useState, useTransition } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import posthog from "posthog-js";
import { createClient } from "@/lib/supabase/client";
import type { DirectoryRow, PageData } from "./queries";
import { DashboardPagination } from "./dashboard-pagination";

const capture=(event:string,properties:Record<string,string|number>)=>{if(posthog.has_opted_in_capturing())posthog.capture(event,properties);};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"AC";
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,character=>character.toUpperCase());

function Students({course,session,onSession}:{course:DirectoryRow;session:string;onSession:(value:string)=>void}){
  const students=course.related||[];
  const exportUrl=session?`/api/academy/classes/${encodeURIComponent(course.id)}/session-export?session=${encodeURIComponent(session)}`:"";
  return <section className="academy-students" role="tabpanel"><div className="academy-student-toolbar"><label>Session<select value={session} onChange={event=>onSession(event.target.value)}><option value="">All sessions</option>{course.sessions?.map(item=><option value={item.id} key={item.id}>{item.primary}</option>)}</select></label>{session?<a className="secondary-action" href={exportUrl} onClick={()=>capture("academy_session_students_exported",{class_id:course.id,session_id:session})}>Export selected session</a>:<button type="button" className="secondary-action" disabled>Choose a session to export</button>}</div>{students.length?<div className="table-scroll" tabIndex={0} aria-label="Scrollable session students"><table className="data-table academy-students-table"><thead><tr><th scope="col">Member</th><th scope="col">Member code</th><th scope="col">Department</th><th scope="col">Progress</th><th scope="col">Status</th></tr></thead><tbody>{students.map(student=><tr key={student.id}><td><div className="identity-cell"><div className="initials">{initials(student.primary)}</div><div><strong>{student.primary}</strong>{student.secondary&&<span>{student.secondary}</span>}</div></div></td><td>{student.details?.membership_code||"—"}</td><td>{student.details?.department_name||"Unassigned"}</td><td><div className="progress-cell"><span>{student.details?.progress_percent||0}%</span><progress max="100" value={Number(student.details?.progress_percent||0)}/></div></td><td><span className={`status-pill status-${student.status.replaceAll("_","-")}`}>{student.status==="completed"?"Completed":"In progress"}</span></td></tr>)}</tbody></table></div>:<p className="modal-empty">No students are assigned to this session.</p>}</section>;
}

function Modules({course}:{course:DirectoryRow}){
  const [message,setMessage]=useState("");
  const open=async(moduleId:string,file:DirectoryRow)=>{try{const client=createClient(),{data,error}=await client.functions.invoke("churchmetric-private-files?action=download",{body:{attachment_id:file.id,attachment_type:"academy_module"}});if(error)throw error;capture("academy_attachment_opened",{class_id:course.id,module_id:moduleId,attachment_id:file.id});window.open(data.url,"_blank","noopener,noreferrer");}catch(error){Sentry.captureException(error,{tags:{route:"academy/classes",action:"attachment_open",record_id:file.id}});setMessage("A private signed link could not be created.");}};
  return <section className="academy-module-tree" role="tabpanel">{message&&<p className="form-error" role="alert">{message}</p>}{course.modules?.length?course.modules.map(module=><details key={module.id} onToggle={event=>{if(event.currentTarget.open)capture("academy_module_expanded",{class_id:course.id,module_id:module.id});}}><summary><span>{module.title}</span><small>{module.attachments.length} {module.attachments.length===1?"attachment":"attachments"}</small></summary>{module.description&&<p>{module.description}</p>}<div className="academy-module-files">{module.attachments.length?module.attachments.map(file=><button type="button" key={file.id} onClick={()=>void open(module.id,file)}><FileIcon size={17}/><span><strong>{file.primary}</strong><small>{file.status}</small></span><DownloadSimpleIcon size={16}/></button>):<span>No attachments.</span>}</div></details>):<p className="modal-empty">No modules configured.</p>}</section>;
}

function ClassDialog({course,session,onSession,onClose}:{course:DirectoryRow;session:string;onSession:(value:string)=>void;onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),[tab,setTab]=useState<"overview"|"modules"|"students">(session?"students":"overview");
  useEffect(()=>{dialog.current?.showModal();},[]);
  const change=(value:typeof tab)=>{setTab(value);capture("academy_class_tab_changed",{class_id:course.id,tab:value});};
  return <dialog ref={dialog} className="action-dialog academy-class-dialog" aria-labelledby="academy-class-title" aria-describedby="academy-class-description" onClose={onClose}><div className="dialog-heading"><div><p className="eyebrow">Academy class</p><h2 id="academy-class-title">{course.primary}</h2><p className="sr-only" id="academy-class-description">Review the class overview, private module attachments, and session students.</p></div><button type="button" onClick={()=>dialog.current?.close()} aria-label="Close class details" title="Close class details"><XIcon size={20}/></button></div><div className="record-dialog-body academy-class-detail"><div className="profile-metrics">{["Modules","Attachments","Students","Sessions","Completion"].map((name,index)=><article key={name}><span>{name}</span><strong>{course.metrics?.[index]||"0"}</strong></article>)}</div><div className="profile-tabs" role="tablist" aria-label="Class details sections">{(["overview","modules","students"]as const).map(value=><button type="button" role="tab" aria-selected={tab===value} onClick={()=>change(value)} key={value}>{label(value)}</button>)}</div>{tab==="overview"?<section className="class-overview" role="tabpanel"><span className="academy-course-code">{course.details?.code||"No course code"}</span><h3>Class overview</h3><p>{course.secondary||"No overview has been provided."}</p></section>:tab==="modules"?<Modules course={course}/>:<Students course={course} session={session} onSession={onSession}/>}</div></dialog>;
}

export function AcademyClassesDirectory({data}:{data:PageData}){
  const router=useRouter(),pathname=usePathname(),params=useSearchParams(),[pending,startTransition]=useTransition(),triggerLabel=useRef("");
  useEffect(()=>{if(!params.get("selected")&&triggerLabel.current)queueMicrotask(()=>document.querySelector<HTMLElement>(`[aria-label="${CSS.escape(triggerLabel.current)}"]`)?.focus());},[params]);
  const update=(values:Record<string,string>)=>{const next=new URLSearchParams(params.toString());for(const[key,value]of Object.entries(values)){if(value)next.set(key,value);else next.delete(key);}startTransition(()=>router.replace(`${pathname}?${next}`,{scroll:false}));};
  const open=(row:DirectoryRow,element:HTMLElement)=>{triggerLabel.current=element.getAttribute("aria-label")||`Open class ${row.primary}`;capture("academy_class_opened",{class_id:row.id,status:row.status});update({selected:row.id,session:""});};
  const close=()=>update({selected:"",session:""});
  return <section className="directory-panel academy-classes-panel" aria-busy={pending}><div className="panel-heading"><div><h2>Class directory</h2><p>Academy classes and learning tracks.</p></div><span>{data.pagination?.total||0} classes</span></div>{data.rows.length?<><div className="table-scroll" tabIndex={0} aria-label="Scrollable academy classes"><table className="data-table academy-classes-table"><thead><tr><th scope="col">Class</th><th scope="col">Track</th><th scope="col">Facilitator</th><th scope="col">Delivery</th><th scope="col">Assigned through</th><th scope="col">Enrolled</th><th scope="col">Completion</th><th scope="col">Status</th></tr></thead><tbody>{data.rows.map(row=><tr role="button" tabIndex={0} aria-label={`Open class ${row.primary}`} onClick={event=>open(row,event.currentTarget)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open(row,event.currentTarget);}}} key={row.id}><td><strong>{row.primary}</strong><small>{row.details?.code||"No code"}</small></td><td>{row.details?.track||"General"}</td><td><div className="identity-cell"><div className="initials">{initials(row.details?.facilitator_name||"")}</div><div><strong>{row.details?.facilitator_name||"Unassigned"}</strong>{row.details?.facilitator_email&&<span>{row.details.facilitator_email}</span>}</div></div></td><td>{row.details?.delivery||"Not scheduled"}</td><td>{row.details?.assigned_through||"Personal"}</td><td>{row.details?.enrolled||0}</td><td><div className="progress-cell"><span>{row.details?.completion||0}%</span><progress max="100" value={Number(row.details?.completion||0)}/></div></td><td><span className={`status-pill status-${row.status}`}>{label(row.status)}</span></td></tr>)}</tbody></table></div>{data.pagination&&<DashboardPagination {...data.pagination} label="Academy class pages"/>}</>:<div className="empty-state"><h3>No classes found</h3><p>No classes match the current authorised filters.</p></div>}{data.academyClass&&<ClassDialog key={`${data.academyClass.id}-${params.get("session")||"all"}`} course={data.academyClass} session={params.get("session")||""} onSession={session=>update({session})} onClose={close}/>}</section>;
}
