"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useRef, useTransition } from "react";
import { FunnelIcon } from "@phosphor-icons/react";
import posthog from "posthog-js";
import type { DirectoryRow } from "./queries";

const periodPaths = new Set(["","analytics","events","soul-winning"]);
const statusPaths = new Set(["members","enquiries","quality-control/reports","quality-control/queries","quality-control/issues","academy/classes","academy/enrolments","academy/instructors"]);

export function DashboardFilters({ pagePath,branches=[] }: { pagePath:string;branches?:DirectoryRow[] }) {
  const router=useRouter(); const pathname=usePathname(); const current=useSearchParams();
  const currentRef=useRef(new URLSearchParams(current.toString()));
  const [pending,startTransition]=useTransition();
  const capture=(event:string,properties:Record<string,string|number>)=>{if(posthog.has_opted_in_capturing())posthog.capture(event,properties);};
  const update=(key:string,value:string)=>{const next=new URLSearchParams(currentRef.current);if(value){next.set(key,value);}else{next.delete(key);}if(key!=="page")next.delete("page");if(key==="range"&&value!=="custom"){next.delete("from");next.delete("to");}currentRef.current=next;if(pagePath===""&&key==="range")capture("dashboard_range_changed",{range:value});if(pagePath===""&&key==="branch")capture("dashboard_campus_changed",{campus:value||"all"});if(pagePath==="analytics"&&key==="range")capture("analytics_period_changed",{period:value});if(pagePath==="analytics"&&key==="category")capture("analytics_category_changed",{category:value||"all"});if(pagePath==="academy/enrolments"&&key==="status")capture("academy_enrolments_filtered",{filter:value||"all"});if(pagePath==="academy/instructors"&&key==="status")capture("academy_instructors_filtered",{filter:value||"all"});startTransition(()=>router.replace(`${pathname}?${next.toString()}`,{scroll:false}));};
  useEffect(()=>{currentRef.current=new URLSearchParams(current.toString());},[current]);
  useEffect(()=>{if(pagePath==="")capture("dashboard_overview_viewed",{range:current.get("range")||"30d",campus:current.get("branch")||"all"});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="analytics")capture("analytics_viewed",{period:current.get("range")||"30d",category:current.get("category")||"all"});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="members")capture("members_viewed",{status:current.get("status")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="events")capture("events_viewed",{period:current.get("range")||"30d",branch:current.get("branch")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="soul-winning")capture("soul_winning_viewed",{period:current.get("range")||"30d",branch:current.get("branch")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="departments")capture("departments_viewed",{branch:current.get("branch")||"all"});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath.startsWith("departments/"))capture("department_detail_viewed",{department_id:pagePath.split("/")[1],branch:current.get("branch")||"all"});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="enquiries")capture("enquiries_viewed",{status:current.get("status")||"all",page:Number(current.get("page")||1),branch:current.get("branch")||"all"});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="quality-control/reports")capture("qc_reports_viewed",{status:current.get("status")||"all",source:current.get("source")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="quality-control/queries")capture("qc_queries_viewed",{status:current.get("status")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="quality-control/issues")capture("qc_issues_viewed",{status:current.get("status")||"all",priority:current.get("priority")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="academy/classes")capture("academy_classes_viewed",{status:current.get("status")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="academy/enrolments")capture("academy_enrolments_viewed",{filter:current.get("status")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="academy/instructors")capture("academy_instructors_viewed",{session_id:current.get("session")||"all",filter:current.get("status")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="targets")capture("targets_viewed",{period:current.get("period")||"all",category:current.get("category")||"all",status:current.get("status")||"all",page:Number(current.get("page")||1)});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(pagePath==="awards")capture("awards_viewed",{period:current.get("period")||"all"});},[pagePath]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="filter-bar" aria-busy={pending}>
    {periodPaths.has(pagePath)&&<label className="filter-select"><span className="sr-only">Period</span><select value={current.get("range")||"30d"} onChange={event=>update("range",event.target.value)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7d">7 days</option><option value="30d">30 days</option><option value="3m">3 months</option><option value="6m">6 months</option><option value="12m">12 months</option><option value="custom">Custom dates</option></select></label>}
    {pagePath==="analytics"&&<label className="filter-select"><span className="sr-only">Report category</span><select value={current.get("category")||"all"} onChange={event=>update("category",event.target.value)}><option value="all">All report categories</option><option value="membership">Membership</option><option value="attendance">Attendance</option><option value="outreach">Outreach</option><option value="departments">Departments</option><option value="academy">Academy</option><option value="care_qc">Care and QC</option></select></label>}
    {(pagePath==="targets"||pagePath==="awards")&&<label className="filter-select"><span className="sr-only">{pagePath==="targets"?"Target":"Award"} period</span><select value={current.get("period")||""} onChange={event=>update("period",event.target.value)}><option value="">All periods</option><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option><option value="year">Annual</option><option value="event">Event</option></select></label>}
    {pagePath==="targets"&&<label className="filter-select"><span className="sr-only">Target category</span><select value={current.get("category")||""} onChange={event=>update("category",event.target.value)}><option value="">All categories</option><option>Membership</option><option>Souls</option><option>Events &amp; Attendance</option><option>App Usage</option></select></label>}
    {pagePath==="targets"&&<label className="filter-select"><FunnelIcon size={15}/><select value={current.get("status")||""} onChange={event=>update("status",event.target.value)} aria-label="Target status"><option value="">All statuses</option><option value="on-track">On track</option><option value="progressing">Progressing</option><option value="at-risk">At risk</option><option value="completed">Completed</option><option value="paused">Paused</option></select></label>}
    {periodPaths.has(pagePath)&&current.get("range")==="custom"&&<><label className="filter-select">From<input type="date" value={current.get("from")||""} max={current.get("to")||undefined} onChange={event=>update("from",event.target.value)}/></label><label className="filter-select">To<input type="date" value={current.get("to")||""} min={current.get("from")||undefined} onChange={event=>update("to",event.target.value)}/></label></>}
    {branches.length>0&&<label className="filter-select"><span className="sr-only">Branch</span><select value={current.get("branch")||""} onChange={event=>update("branch",event.target.value)}><option value="">All branches</option>{branches.map(branch=><option value={branch.id} key={branch.id}>{branch.primary}</option>)}</select></label>}
    {pagePath==="members"&&<label className="filter-select"><FunnelIcon size={15}/><select value={current.get("filter")||""} onChange={event=>update("filter",event.target.value)} aria-label="Member date filter"><option value="">All members</option><option value="recent">Recently Added</option></select></label>}
    {pagePath==="members"&&<label className="filter-select"><span className="sr-only">Sort members</span><select value={current.get("sort")||"newest"} onChange={event=>update("sort",event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name_asc">Name A–Z</option><option value="name_desc">Name Z–A</option><option value="last_seen">Last seen</option><option value="membership_code_asc">Membership code ascending</option><option value="membership_code_desc">Membership code descending</option></select></label>}
    {pagePath==="quality-control/reports"&&<label className="filter-select"><span className="sr-only">Reporter source</span><select value={current.get("source")||""} onChange={event=>update("source",event.target.value)}><option value="">All reporters</option><option value="member">Members</option><option value="leader">Leaders</option></select></label>}
    {pagePath==="quality-control/issues"&&<label className="filter-select"><span className="sr-only">Priority</span><select value={current.get("priority")||""} onChange={event=>update("priority",event.target.value)}><option value="">All priorities</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label>}
    {statusPaths.has(pagePath)&&<label className="filter-select"><FunnelIcon size={15}/><select value={current.get("status")||""} onChange={event=>update("status",event.target.value)} aria-label="Status"><option value="">All statuses</option>{pagePath==="enquiries"?<><option value="open">Open</option><option value="in_progress">In review</option><option value="urgent">Urgent</option><option value="closed">Closed</option></>:pagePath==="quality-control/reports"?<><option value="open">Open</option><option value="in_review">In review</option><option value="resolved">Resolved</option><option value="closed">Closed</option></>:pagePath==="quality-control/queries"?<><option value="open">Open</option><option value="awaiting_response">Awaiting response</option><option value="overdue">Overdue</option><option value="responded">Responded</option><option value="closed">Closed</option></>:pagePath==="quality-control/issues"?<><option value="open">Open</option><option value="investigating">Investigating</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></>:pagePath==="academy/classes"?<><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></>:pagePath==="academy/enrolments"?<><option value="finished">Finished</option><option value="unfinished">Unfinished</option><option value="yet_to_attend">Yet to attend</option></>:pagePath==="academy/instructors"?<><option value="active">Active</option><option value="inactive">Inactive</option></>:<><option value="active">Active</option>{pagePath!=="members"&&<><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="resolved">Resolved</option></>}<option value="inactive">Inactive</option></>}</select></label>}
  </div>;
}
