"use client";
import { useEffect, useRef, useState } from "react";
import { DownloadSimpleIcon, TrashIcon, UploadSimpleIcon } from "@phosphor-icons/react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import posthog from "posthog-js";
import * as Sentry from "@sentry/nextjs";
import { createClient } from "@/lib/supabase/client";
import type { DirectoryRow } from "./queries";

export function DepartmentAttachments({departmentId,branchId,attachments}:{departmentId:string;branchId?:string;attachments:DirectoryRow[]}){
  const router=useRouter(),input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[previews,setPreviews]=useState<Record<string,string>>({});
  const invoke=async(action:string,body:FormData|{attachment_id:string})=>{const client=createClient();const {data,error}=await client.functions.invoke(`churchmetric-private-files?action=${action}`,{body});if(error)throw error;return data;};
  useEffect(()=>{let active=true;Promise.all(attachments.filter(item=>item.secondary.startsWith("image/")).map(async item=>{try{const data=await invoke("download",{attachment_id:item.id});return [item.id,data.url] as const;}catch{return null;}})).then(values=>{if(active)setPreviews(Object.fromEntries(values.filter(Boolean) as Array<readonly[string,string]>));});return()=>{active=false};},[attachments]);
  const report=(error:unknown,action:string,attachmentId?:string)=>Sentry.captureException(error,{tags:{route:"departments/detail",action,record_id:attachmentId||departmentId}});
  const upload=async(files:FileList|File[])=>{if(!files.length)return;if(!branchId){setMessage("Select a branch before uploading private files.");return;}setBusy(true);setMessage("");try{for(const file of Array.from(files)){const form=new FormData();form.set("department_id",departmentId);form.set("branch_id",branchId);form.set("file",file);await invoke("upload",form);}if(posthog.has_opted_in_capturing())posthog.capture("department_attachment_uploaded",{count:files.length,department_id:departmentId});setMessage(`${files.length} attachment(s) uploaded.`);router.refresh();}catch(error){report(error,"attachment_upload");setMessage("Upload failed. Check the file type, size, and private bucket configuration.");}finally{setBusy(false);}};
  const download=async(item:DirectoryRow)=>{try{const data=await invoke("download",{attachment_id:item.id});if(posthog.has_opted_in_capturing())posthog.capture("department_attachment_opened",{attachment_id:item.id,department_id:departmentId});window.open(data.url,"_blank","noopener,noreferrer");}catch(error){report(error,"attachment_open",item.id);setMessage("A signed download link could not be created.");}};
  const remove=async(item:DirectoryRow)=>{if(!window.confirm(`Delete ${item.primary}?`))return;setBusy(true);try{await invoke("delete",{attachment_id:item.id});if(posthog.has_opted_in_capturing())posthog.capture("department_attachment_deleted",{attachment_id:item.id,department_id:departmentId});router.refresh();}catch(error){report(error,"attachment_delete",item.id);setMessage("Attachment could not be deleted.");}finally{setBusy(false);}};
  return <section className="attachment-panel"><div className="panel-heading"><div><h2>Attachments</h2><p>Private department files. Signed links expire after five minutes.</p></div><button type="button" className="secondary-action" disabled={busy} onClick={()=>input.current?.click()}><UploadSimpleIcon size={15}/> Upload</button></div><input ref={input} hidden type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,text/plain,text/csv,.docx,.xlsx" onChange={event=>event.target.files&&upload(event.target.files)}/><div className="attachment-dropzone" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void upload(event.dataTransfer.files);}}><UploadSimpleIcon size={20}/><span>Drop files here or use Upload. Maximum 10 MB each.</span></div>{message&&<p className={message.includes("failed")||message.includes("could not")?"form-error":"form-success"} role="status">{message}</p>}<div className="attachment-grid">{attachments.length?attachments.map(item=><article key={item.id}>{previews[item.id]?<Image unoptimized width={240} height={94} src={previews[item.id]} alt=""/>:<div className="file-thumbnail">{item.secondary.startsWith("image/")?"IMG":"FILE"}</div>}<strong>{item.primary}</strong><span>{item.meta}</span><div><button type="button" onClick={()=>download(item)} aria-label={`Open ${item.primary}`}><DownloadSimpleIcon size={14}/></button><button type="button" onClick={()=>remove(item)} aria-label={`Delete ${item.primary}`}><TrashIcon size={14}/></button></div></article>):<p>No attachments uploaded.</p>}</div></section>;
}
