"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckIcon, EyeIcon, EyeSlashIcon, InfoIcon, LockSimpleIcon, PaperPlaneTiltIcon, PencilSimpleIcon, XIcon } from "@phosphor-icons/react";
import type { DirectoryRow } from "./queries";
import { BusyLabel } from "@/components/loading-spinner";

const editableFields=[{key:"full_name",label:"Full name"},{key:"phone",label:"Phone"},{key:"email",label:"Email",type:"email"}] as const;
const date=(value?:string)=>{if(!value)return"—";const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?"—":parsed.toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"});};
const relative=(value?:string)=>{if(!value)return"Never";const then=new Date(value).valueOf();if(!Number.isFinite(then))return"Never";const days=Math.floor((Date.now()-then)/86400000);if(days<=0)return"Today";if(days===1)return"Yesterday";if(days<7)return`${days} days ago`;return new Date(then).toLocaleDateString("en-NG",{month:"short",day:"numeric"});};

export function MemberDetailsEditor({row,departments,onSaved}:{row:DirectoryRow;departments:DirectoryRow[];onSaved:()=>Promise<void>}){
  const details=row.sections?.["Personal details"]?.[0]?.details||{};
  const initialDepartments=useMemo(()=>(details.department_ids||"").split(",").filter(Boolean),[details.department_ids]);
  const initialValues=useMemo(()=>Object.fromEntries(editableFields.map(field=>[field.key,details[field.key]||""])),[details]);
  const[activeField,setActiveField]=useState<string|null>(null),[authorize,setAuthorize]=useState(false),[values,setValues]=useState<Record<string,string>>(initialValues),[selectedDepartments,setSelectedDepartments]=useState<string[]>(initialDepartments),[method,setMethod]=useState<"password"|"otp">("password"),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[otp,setOtp]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0);
  useEffect(()=>{setValues(initialValues);setSelectedDepartments(initialDepartments);setActiveField(null);},[initialValues,initialDepartments]);
  useEffect(()=>{if(cooldown<=0)return;const timer=window.setInterval(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer);},[cooldown]);
  const dirty=editableFields.some(field=>(values[field.key]||"")!==(initialValues[field.key]||""))||selectedDepartments.join(",")!==initialDepartments.join(",");
  const reset=()=>{setValues(initialValues);setSelectedDepartments(initialDepartments);setActiveField(null);setError("");};
  const request=async(body:Record<string,unknown>)=>{const response=await fetch(`/api/members/${encodeURIComponent(row.id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),payload=await response.json();if(!response.ok){if(Number(payload.retry_after)>0)setCooldown(Number(payload.retry_after));throw new Error(payload.error||"The request could not be completed");}return payload;};
  const sendOtp=async()=>{setBusy(true);setError("");try{const payload=await request({action:"request_otp"});setCooldown(Number(payload.cooldown_seconds)||60);setMessage(`Code sent to ${payload.email_masked}.`);}catch(reason){setError(reason instanceof Error?reason.message:"Code could not be sent");}finally{setBusy(false);}};
  const save=async()=>{setBusy(true);setError("");try{await request({action:"update",verification_method:method,password:method==="password"?password:undefined,otp:method==="otp"?otp:undefined,changes:values,department_ids:selectedDepartments});setAuthorize(false);setPassword("");setOtp("");setMessage("Member details updated and notification email sent.");await onSaved();}catch(reason){setError(reason instanceof Error?reason.message:"Details could not be updated");}finally{setBusy(false);}};
  const addDepartment=(id:string)=>{if(id&&!selectedDepartments.includes(id))setSelectedDepartments(current=>[...current,id]);};
  const locked=[{label:"Member code",value:details.membership_code},{label:"Membership stage",value:row.status},{label:"Date joined",value:date(details.date_joined||details.created_at)},{label:"Last seen",value:relative(details.last_seen_at)}];

  return <>
    <div className="member-detail-grid">
      {editableFields.slice(0,1).map(field=><EditableCard key={field.key} field={field} active={activeField===field.key} value={values[field.key]||""} activate={()=>setActiveField(field.key)} change={value=>setValues(current=>({...current,[field.key]:value}))}/>) }
      <LockedCard {...locked[0]}/>
      {editableFields.slice(1).map(field=><EditableCard key={field.key} field={field} active={activeField===field.key} value={values[field.key]||""} activate={()=>setActiveField(field.key)} change={value=>setValues(current=>({...current,[field.key]:value}))}/>) }
      <div className={`member-detail-card department-detail-card ${activeField==="departments"?"editing":""}`} role="button" tabIndex={0} onClick={()=>setActiveField("departments")} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setActiveField("departments");}}}><span>Departments</span><PencilSimpleIcon className="detail-card-icon" size={17}/>{activeField==="departments"?<><div className="department-tags">{selectedDepartments.map(id=>{const department=departments.find(item=>item.id===id);return <span key={id}>{department?.primary||"—"}<button type="button" onClick={event=>{event.stopPropagation();setSelectedDepartments(current=>current.filter(value=>value!==id));}} aria-label={`Remove ${department?.primary||"department"}`}><XIcon size={12}/></button></span>;})}</div><select autoFocus value="" onClick={event=>event.stopPropagation()} onChange={event=>addDepartment(event.target.value)}><option value="">Add department</option>{departments.filter(item=>!selectedDepartments.includes(item.id)).map(item=><option value={item.id} key={item.id}>{item.primary}</option>)}</select></>:<strong>{selectedDepartments.map(id=>departments.find(item=>item.id===id)?.primary).filter(Boolean).join(", ")||"Unassigned"}</strong>}</div>
      <LockedCard {...locked[1]}/><LockedCard {...locked[2]}/><LockedCard {...locked[3]}/>
    </div>
    {message&&<p className="form-success member-update-message" role="status">{message}</p>}
    {dirty&&<footer className="member-update-footer"><p><InfoIcon size={16}/>Unsaved profile changes</p><div><button type="button" onClick={reset}>Cancel changes</button><button type="button" className="primary-action" onClick={()=>setAuthorize(true)}><CheckIcon size={17}/>Update details</button></div></footer>}
    {authorize&&<div className="authorization-layer" role="dialog" aria-modal="true" aria-labelledby="authorize-title"><section className="authorization-dialog"><header><div><h2 id="authorize-title">Authorize profile update</h2><p>Confirm changes to {row.primary}</p></div><button type="button" onClick={()=>setAuthorize(false)} aria-label="Close authorization"><XIcon size={19}/></button></header><div className="authorization-tabs"><button type="button" className={method==="password"?"active":""} onClick={()=>setMethod("password")}>Password</button><button type="button" className={method==="otp"?"active":""} onClick={()=>setMethod("otp")}>One-time code</button></div>{method==="password"?<label className="authorization-field"><span>Admin password</span><div><input type={showPassword?"text":"password"} value={password} onChange={event=>setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Hide password":"Show password"}>{showPassword?<EyeSlashIcon size={17}/>:<EyeIcon size={17}/>}</button></div><small>Use the password for the signed-in administrator account.</small></label>:<label className="authorization-field"><span>One-time code</span><div className="otp-entry"><input inputMode="numeric" maxLength={6} value={otp} onChange={event=>setOtp(event.target.value.replace(/\D/g,""))} placeholder="000000"/><button type="button" disabled={busy||cooldown>0} onClick={()=>void sendOtp()}>{busy?<BusyLabel label="Sending"/>:<><PaperPlaneTiltIcon size={16}/>{cooldown>0?`Resend in ${cooldown}s`:"Send code"}</>}</button></div><small>The code is sent to the currently signed-in administrator&apos;s email.</small></label>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<footer><button type="button" onClick={()=>setAuthorize(false)}>Cancel</button><button type="button" className="primary-action" aria-busy={busy} disabled={busy||(method==="password"?!password:otp.length!==6)} onClick={()=>void save()}>{busy?<BusyLabel label="Updating"/>:<><LockSimpleIcon size={16}/>Authorize & update</>}</button></footer></section></div>}
  </>;
}

function EditableCard({field,active,value,activate,change}:{field:{key:string;label:string;type?:string};active:boolean;value:string;activate:()=>void;change:(value:string)=>void}){return <div className={`member-detail-card ${active?"editing":""}`} role="button" tabIndex={0} onClick={activate} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();activate();}}}><span>{field.label}</span><PencilSimpleIcon className="detail-card-icon" size={17}/>{active?<input autoFocus type={field.type||"text"} value={value} aria-label={field.label} onClick={event=>event.stopPropagation()} onChange={event=>change(event.target.value)}/>:<strong>{value||"—"}</strong>}</div>;}
function LockedCard({label,value}:{label:string;value?:string}){return <div className="member-detail-card locked"><span>{label}</span><LockSimpleIcon className="detail-card-icon" size={15}/><strong>{value||"—"}</strong></div>;}
