"use server";

import * as Sentry from "@sentry/nextjs";
import type { SupabaseClient } from "@supabase/supabase-js";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { resolveAdminContext } from "@/lib/permissions/admin-context";

export type MutationState={ok?:boolean;error?:string;message?:string;recordId?:string};
type AdminContext={client:SupabaseClient;userId:string;branchId:string;role:string};
const required=(form:FormData,key:string,label:string)=>{const value=String(form.get(key)||"").trim();if(!value)throw new Error(`${label} is required.`);return value;};
const validEmail=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);

async function requireAdmin():Promise<AdminContext>{
  const typedClient=await createClient();const context=await resolveAdminContext(typedClient as unknown as SupabaseClient);
  if(!context)throw new Error("Administrator access is required.");
  if(!context.branchId&&context.role!=="globaladmin")throw new Error("Your administrator account is missing a branch assignment.");
  return {client:typedClient as unknown as SupabaseClient,userId:context.userId,branchId:context.branchId,role:context.role};
}
const failure=(error:unknown,action:string):MutationState=>{const message=error instanceof Error?error.message:"The request could not be completed.";if(message.includes("required")||message.includes("must")||message.includes("cannot")||message.includes("access"))return{error:message};Sentry.captureException(error,{tags:{action}});return{error:"The request could not be completed. Try again."};};
const functionErrorMessage=async(error:unknown)=>{if(!error||typeof error!=="object")return null;const context="context" in error?error.context:null;if(!context||typeof context!=="object"||!("json" in context)||typeof context.json!=="function")return null;const payload=await context.json().catch(()=>null);return payload&&typeof payload.error==="string"?payload.error:null;};

export async function createMember(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const branchId=ctx.role==="globaladmin"?required(form,"branch_id","Branch"):ctx.branchId;const email=required(form,"email","Email").toLowerCase();if(!validEmail(email))throw new Error("Email must be a valid address.");const fullName=required(form,"full_name","Full name");if(fullName.length>160)throw new Error("Full name must be 160 characters or fewer.");const phone=String(form.get("phone")||"").trim();if(phone.length>40)throw new Error("Phone must be 40 characters or fewer.");const departmentIds=form.getAll("department_id").map(value=>String(value)).filter(Boolean);const {data,error}=await ctx.client.functions.invoke("create-churchmetric-member",{body:{branch_id:branchId,full_name:fullName,email,phone:phone||null,department_ids:departmentIds}});if(error)throw new Error(await functionErrorMessage(error)||error.message||"Member creation service is unavailable.");const member=data?.member;if(!member?.display_code)throw new Error("Member was created but the membership code was not returned.");revalidatePath("/dashboard");revalidatePath("/dashboard/members");return{ok:true,message:member.onboarding_email_sent?`Member created. Membership code: ${member.display_code}. Onboarding email sent.`:`Member created. Membership code: ${member.display_code}. The onboarding email could not be sent.`};}catch(error){Sentry.captureException(error,{tags:{action:"member_created"}});return{error:error instanceof Error?error.message:"Member creation could not be completed."};}}

export async function createSoul(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const eventId=required(form,"event_id","Evangelism event"),fullName=required(form,"full_name","Full name"),branchId=ctx.role==='globaladmin'?required(form,"branch_id","Branch"):ctx.branchId,email=String(form.get("email")||"").trim().toLowerCase(),phone=String(form.get("phone")||"").trim(),location=String(form.get("location")||"").trim(),evangelist=String(form.get("evangelist_name")||"").trim();if(fullName.length>160)throw new Error("Full name must be 160 characters or fewer.");if(email&&!validEmail(email))throw new Error("Email must be a valid address.");if(phone.length>40)throw new Error("Phone must be 40 characters or fewer.");if(location.length>160||evangelist.length>160)throw new Error("Location and evangelist must be 160 characters or fewer.");const {error}=await ctx.client.rpc("churchmetric_create_soul_v1",{p_branch_id:branchId,p_event_id:eventId,p_full_name:fullName,p_email:email||null,p_phone:phone||null,p_location:location||null,p_evangelist_name:evangelist||null});if(error)throw error;revalidatePath("/dashboard/soul-winning");return{ok:true,message:"Soul added with an initial follow-up assignment."};}catch(error){return failure(error,"soul_created");}}

export async function transitionSoul(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const nextStatus=required(form,"next_status","Next status");if(!["contacted","integrating","integrated","closed"].includes(nextStatus))throw new Error("Next status is invalid.");const {error}=await ctx.client.rpc("churchmetric_transition_soul",{p_soul_id:required(form,"soul_id","Soul"),p_next_status:nextStatus,p_notes:String(form.get("notes")||"").trim()||null});if(error)throw error;revalidatePath("/dashboard/soul-winning");return{ok:true};}catch(error){return failure(error,"soul_status_changed");}}

export async function createEnquiry(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const branchId=ctx.role==='globaladmin'?required(form,"branch_id","Branch"):ctx.branchId;const {error}=await ctx.client.from("enquiries").insert({branch_id:branchId,category:required(form,"category","Category"),subject:required(form,"subject","Subject"),body:required(form,"body","Message"),priority:String(form.get("priority")||"medium"),created_by:ctx.userId});if(error)throw error;revalidatePath("/dashboard/enquiries");return{ok:true};}catch(error){return failure(error,"enquiry_created");}}

export async function replyToEnquiry(_:MutationState,form:FormData):Promise<MutationState>{const enquiryId=String(form.get("enquiry_id")||"");return Sentry.startSpan({name:"enquiries.reply",op:"db.rpc",attributes:{route:"enquiries",action:"reply",record_id:enquiryId}},async()=>{try{const ctx=await requireAdmin();const body=required(form,"body","Reply");if(body.length>4000)throw new Error("Reply must be 4,000 characters or fewer.");const {data,error}=await ctx.client.rpc("churchmetric_reply_to_enquiry_v1",{p_enquiry_id:required(form,"enquiry_id","Enquiry"),p_body:body});if(error)throw error;revalidatePath("/dashboard/enquiries");const delivery=(data&&typeof data==="object"&&"delivery_status" in data)?String(data.delivery_status):"queued";return{ok:true,message:delivery==="queued"?"Reply appended and queued for email delivery.":"Reply appended."};}catch(error){return failure(error,"enquiry_response_sent");}});}

export async function setEnquiryStatus(_:MutationState,form:FormData):Promise<MutationState>{const enquiryId=String(form.get("enquiry_id")||"");return Sentry.startSpan({name:"enquiries.status",op:"db.rpc",attributes:{route:"enquiries",action:"status",record_id:enquiryId}},async()=>{try{const ctx=await requireAdmin();const status=required(form,"status","Status");if(!["open","in_progress","resolved","closed"].includes(status))throw new Error("Status must be open, in review, resolved, or closed.");const {error}=await ctx.client.rpc("churchmetric_set_enquiry_status_v1",{p_enquiry_id:required(form,"enquiry_id","Enquiry"),p_status:status});if(error)throw error;revalidatePath("/dashboard/enquiries");return{ok:true,message:"Enquiry status updated."};}catch(error){return failure(error,"enquiry_status_changed");}});}

export async function assignEnquiry(_:MutationState,form:FormData):Promise<MutationState>{const enquiryId=String(form.get("enquiry_id")||"");return Sentry.startSpan({name:"enquiries.assign",op:"db.rpc",attributes:{route:"enquiries",action:"assign",record_id:enquiryId}},async()=>{try{const ctx=await requireAdmin();const handlerId=String(form.get("handler_id")||"").trim()||null;const {error}=await ctx.client.rpc("churchmetric_assign_enquiry_v1",{p_enquiry_id:required(form,"enquiry_id","Enquiry"),p_handler_id:handlerId});if(error)throw error;revalidatePath("/dashboard/enquiries");return{ok:true,message:handlerId?"Handler assigned.":"Handler cleared."};}catch(error){return failure(error,"enquiry_handler_assigned");}});}

export async function assignQualityQuery(_:MutationState,form:FormData):Promise<MutationState>{const assigneeCount=form.getAll("assignee_id").length;return Sentry.startSpan({name:"quality_queries.create",op:"db.rpc",attributes:{route:"quality-control/queries",action:"create",assignee_count:assigneeCount}},async()=>{try{const ctx=await requireAdmin();const branchId=ctx.role==='globaladmin'?required(form,"branch_id","Branch"):ctx.branchId;const assignees=Array.from(new Set(form.getAll("assignee_id").map(String).filter(Boolean)));if(!assignees.length)throw new Error("At least one assignee is required.");const issued=new Date(required(form,"issued_at","Issue date")),due=new Date(required(form,"due_at","Due date"));if(Number.isNaN(issued.valueOf())||Number.isNaN(due.valueOf()))throw new Error("Issue date and due date must be valid.");if(due<issued)throw new Error("Due date cannot precede issue date.");const {data,error}=await ctx.client.rpc("churchmetric_create_quality_query_v3",{p_branch_id:branchId,p_category:required(form,"category","Category"),p_subject:required(form,"subject","Subject"),p_body:required(form,"body","Details"),p_priority:String(form.get("priority")||"medium"),p_issued_at:issued.toISOString(),p_due_at:due.toISOString(),p_assignee_ids:assignees});if(error)throw error;revalidatePath("/dashboard/quality-control/queries");return{ok:true,message:"Query assigned.",recordId:String(data||"")};}catch(error){return failure(error,"quality_query_created");}});}

export async function createCampaign(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const branchId=ctx.role==='globaladmin'?required(form,"branch_id","Branch"):ctx.branchId;const channel=required(form,"channel","Channel").toLowerCase();if(channel!=="email")throw new Error("Only email campaigns are available.");const subject=String(form.get("subject")||"").trim();if(!subject)throw new Error("Subject is required for email campaigns.");const audience=String(form.get("audience")||"individuals");if(!["individuals","all","departments","souls","leaders"].includes(audience))throw new Error("Audience category is invalid.");let destinations=form.getAll("destination").map(value=>String(value).trim().toLowerCase()).filter(validEmail);if(audience!=="individuals"){let table="profiles",column="email";if(audience==="souls")table="souls";if(audience==="leaders"){table="department_leadership_view";column="user_email";}let query=ctx.client.from(table).select(column).eq("branch_id",branchId).limit(5000);if(audience==="departments")query=query.not("department_id","is",null);if(audience==="leaders")query=query.eq("is_active",true);const {data,error}=await query;if(error)throw error;destinations=(data||[]).map(row=>String(((row as unknown) as Record<string,unknown>)[column]||"").trim().toLowerCase()).filter(validEmail);}destinations=Array.from(new Set(destinations));if(!destinations.length)throw new Error("The selected audience has no deliverable email addresses.");const scheduled=String(form.get("scheduled_at")||"");const scheduledAt=scheduled?new Date(scheduled):null;if(scheduledAt&&Number.isNaN(scheduledAt.valueOf()))throw new Error("Schedule must be a valid date and time.");const {error}=await ctx.client.rpc("churchmetric_create_email_campaign_v1",{p_branch_id:branchId,p_name:required(form,"name","Campaign name"),p_subject:subject,p_body:required(form,"body","Message"),p_scheduled_at:scheduledAt?.toISOString()||null,p_audience_category:audience,p_recipients:destinations.map(destination=>({destination}))});if(error)throw error;revalidatePath("/dashboard/follow-ups");return{ok:true,message:`Campaign queued for ${destinations.length} unique recipients.`};}catch(error){return failure(error,"campaign_created");}}

export async function createTarget(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const branchId=ctx.role==='globaladmin'?required(form,"branch_id","Branch"):ctx.branchId,current=Number(form.get("current_value")||0),goal=Number(required(form,"goal_value","Goal")),step=Number(form.get("progress_step")||1),starts=new Date(required(form,"starts_at","Start date")),ends=new Date(required(form,"ends_at","End date")),period=required(form,"period_type","Period"),channels=form.getAll("notification_channel").map(String);if(!["day","week","month","year","event"].includes(period))throw new Error("Period is invalid.");if(!Number.isFinite(current)||!Number.isFinite(goal)||!Number.isFinite(step)||current<0||goal<=0||step<=0)throw new Error("Current value cannot be negative; goal and progress step must be positive.");if(Number.isNaN(starts.valueOf())||Number.isNaN(ends.valueOf())||ends<starts)throw new Error("End date cannot precede start date.");if(channels.some(channel=>!["in_app","email"].includes(channel)))throw new Error("Notification channel is unavailable.");const {data,error}=await ctx.client.rpc("churchmetric_create_target_v1",{p_branch_id:branchId,p_title:required(form,"title","Title"),p_metric:required(form,"metric","Metric"),p_period_type:period,p_period_label:required(form,"period_label","Period or event label"),p_starts_at:starts.toISOString(),p_ends_at:ends.toISOString(),p_current_value:current,p_goal_value:goal,p_progress_step:step,p_notification_channels:channels});if(error)throw error;revalidatePath("/dashboard/targets");return{ok:true,message:"Target created.",recordId:String(data||"")};}catch(error){return failure(error,"target_created");}}

export async function addTargetProgress(_:MutationState,form:FormData):Promise<MutationState>{try{const ctx=await requireAdmin();const targetId=required(form,"target_id","Target"),delta=Number(required(form,"delta","Progress"));if(!Number.isFinite(delta)||delta===0)throw new Error("Progress must be a non-zero number.");const {data,error}=await ctx.client.rpc("churchmetric_add_target_progress",{p_target_id:targetId,p_delta:delta,p_idempotency_key:required(form,"idempotency_key","Update token"),p_source_type:"manual",p_source_id:null});if(error)throw error;const result=Array.isArray(data)?data[0]:data as {achieved?:boolean}|null;revalidatePath("/dashboard/targets");return{ok:true,message:result?.achieved?"Target hit and trophy awarded.":"Progress updated."};}catch(error){return failure(error,"target_progress_added");}}

export async function transitionQualityIssue(_:MutationState,form:FormData):Promise<MutationState>{const issueId=String(form.get("issue_id")||""),nextStatus=String(form.get("next_status")||"");return Sentry.startSpan({name:"quality_issues.transition",op:"db.rpc",attributes:{route:"quality-control/issues",record_id:issueId,action:"transition",next_status:nextStatus}},async()=>{try{const ctx=await requireAdmin();if(!["investigating","in_progress","resolved"].includes(nextStatus))throw new Error("Next status is invalid.");const note=String(form.get("note")||"").trim();if(note.length>2000)throw new Error("Transition note must be 2,000 characters or fewer.");const {error}=await ctx.client.rpc("churchmetric_transition_quality_issue",{p_issue_id:required(form,"issue_id","Issue"),p_next_status:nextStatus,p_note:note||null});if(error)throw error;revalidatePath("/dashboard/quality-control/issues");return{ok:true,message:nextStatus==="resolved"?"Issue resolved.":`Issue moved to ${nextStatus.replaceAll("_"," ")}.`};}catch(error){return failure(error,"quality_issue_transitioned");}});}

export async function transitionQualityReport(_:MutationState,form:FormData):Promise<MutationState>{const reportId=String(form.get("report_id")||""),actionName=String(form.get("report_action")||"");return Sentry.startSpan({name:"quality_reports.transition",op:"db.rpc",attributes:{route:"quality-control/reports",record_id:reportId,action:actionName}},async()=>{try{const ctx=await requireAdmin();const action=required(form,"report_action","Action");if(!["resolve","escalate","reopen"].includes(action))throw new Error("Action must be resolve, escalate, or reopen.");const {error}=await ctx.client.rpc("churchmetric_transition_quality_report",{p_report_id:required(form,"report_id","Report"),p_action:action});if(error)throw error;revalidatePath("/dashboard/quality-control/reports");revalidatePath("/dashboard/quality-control/issues");return{ok:true,message:`Report ${action === "resolve" ? "resolved" : action === "escalate" ? "escalated" : "reopened"}.`};}catch(error){return failure(error,"quality_report_transitioned");}});}

export async function assignQualityReport(_:MutationState,form:FormData):Promise<MutationState>{const reportId=String(form.get("report_id")||"");return Sentry.startSpan({name:"quality_reports.assign",op:"db.rpc",attributes:{route:"quality-control/reports",record_id:reportId,action:"assign"}},async()=>{try{const ctx=await requireAdmin();const assigneeId=String(form.get("assignee_id")||"").trim()||null;const {error}=await ctx.client.rpc("churchmetric_assign_quality_report",{p_report_id:required(form,"report_id","Report"),p_assignee_id:assigneeId});if(error)throw error;revalidatePath("/dashboard/quality-control/reports");return{ok:true,message:assigneeId?"Investigator assigned.":"Assignment cleared."};}catch(error){return failure(error,"quality_report_assigned");}});}
