"use client";

import { useActionState, useEffect, useRef, useState } from "react";
import { DownloadSimpleIcon, PlusIcon, XIcon } from "@phosphor-icons/react";
import posthog from "posthog-js";
import * as Sentry from "@sentry/nextjs";
import type { DirectoryRow } from "./queries";
import { assignQualityQuery, createCampaign, createEnquiry, createMember, createSoul, createTarget, type MutationState } from "./mutations";

type FormAction=(state:MutationState,data:FormData)=>Promise<MutationState>;
const actionMap:Record<string,FormAction>={"":createMember,members:createMember,"soul-winning":createSoul,enquiries:createEnquiry,"quality-control/queries":assignQualityQuery,"follow-ups":createCampaign,targets:createTarget};
const exportPaths=new Set(["analytics","members","departments"]);
const csvCell=(value:string)=>`"${value.replaceAll('"','""')}"`;
const exportCsv=(path:string,rows:DirectoryRow[])=>path==="analytics"?["Category,Indicator,Current,Previous,Change,Status",...rows.map(item=>[item.secondary,item.primary,item.details?.current||"0",item.details?.previous||"0",item.details?.change||"0%",item.status].map(csvCell).join(","))].join("\r\n"):path==="departments"?["Department,Description,Leader,Title,Members,Attendance rate",...rows.map(item=>[item.primary,item.secondary,item.details?.leader||"Unassigned",item.details?.leader_title||"No active leader",item.details?.member_count||"0",`${item.details?.attendance_rate||"0"}%`].map(csvCell).join(","))].join("\r\n"):["Record,Secondary,Status,Date",...rows.map(item=>[item.primary,item.secondary,item.status,item.meta].map(csvCell).join(","))].join("\r\n");

function AssigneeTags({choices}:{choices:DirectoryRow[]}){
  const [selected,setSelected]=useState<string[]>([]);
  const available=choices.filter(choice=>!selected.includes(choice.id));
  const add=(id:string)=>{if(!id)return;setSelected(current=>[...current,id]);if(posthog.has_opted_in_capturing())posthog.capture("qc_query_assignee_added",{assignee_count:selected.length+1});};
  return <fieldset className="assignee-picker"><legend>Assignees</legend><div className="assignee-tags">{selected.map(id=>{const member=choices.find(choice=>choice.id===id);return <span key={id}>{member?.primary||"Member"}<input type="hidden" name="assignee_id" value={id}/><button type="button" onClick={()=>setSelected(current=>current.filter(value=>value!==id))} aria-label={`Remove ${member?.primary||"assignee"}`}><XIcon size={14}/></button></span>;})}</div><label>Add assignee<select value="" onChange={event=>add(event.target.value)}><option value="">Select member</option>{available.map(member=><option value={member.id} key={member.id}>{member.primary}{member.secondary?` — ${member.secondary}`:""}</option>)}</select></label>{!selected.length&&<p className="field-help">Select at least one assignee. Added assignees appear as keyboard-removable tags.</p>}</fieldset>;
}

function MemberNameFields(){const[first,setFirst]=useState(""),[last,setLast]=useState("");return <><input type="hidden" name="full_name" value={`${first} ${last}`.trim()}/><div className="form-columns"><label>First name<input value={first} onChange={event=>setFirst(event.target.value)} placeholder="First name" required/></label><label>Last name<input value={last} onChange={event=>setLast(event.target.value)} placeholder="Last name" required/></label></div></>;}
function DepartmentTags({choices}:{choices:DirectoryRow[]}){const[selected,setSelected]=useState<string[]>([]),available=choices.filter(choice=>!selected.includes(choice.id));const add=(id:string)=>{if(id)setSelected(current=>[...current,id]);};return <fieldset className="department-picker"><legend>Departments</legend><div className="department-tags">{selected.map(id=>{const department=choices.find(choice=>choice.id===id);return <span key={id}>{department?.primary||"Department"}<input type="hidden" name="department_id" value={id}/><button type="button" onClick={()=>setSelected(current=>current.filter(value=>value!==id))} aria-label={`Remove ${department?.primary||"department"}`}><XIcon size={13}/></button></span>;})}</div><label>Add department<select value="" onChange={event=>add(event.target.value)}><option value="">Select department</option>{available.map(department=><option value={department.id} key={department.id}>{department.primary}</option>)}</select></label></fieldset>;}

function QueryDates(){
  const [issued,setIssued]=useState("");
  return <div className="form-columns"><label>Issue date<input name="issued_at" type="datetime-local" value={issued} onChange={event=>setIssued(event.target.value)} required/></label><label>Due date<input name="due_at" type="datetime-local" min={issued||undefined} required/></label></div>;
}

const targetMetricGroups=[
  {label:"Membership",metrics:["Total Membership","New Members Joined","Active Members","Member Retention Rate"]},
  {label:"Souls",metrics:["Number of Souls Won","Souls in Follow-up","Souls Integrated","Outreach Campaigns Completed"]},
  {label:"Events & Attendance",metrics:["Service Attendance","Event Registrations","Event Attendance Rate","Number of Events Held"]},
  {label:"App Usage",metrics:["Monthly Active Users","App Adoption Rate","Mobile Check-ins","Actions Completed in App"]},
] as const;

function TargetMetricSelector(){
  const[query,setQuery]=useState(""),[selected,setSelected]=useState("");const needle=query.trim().toLowerCase();
  return <fieldset className="target-metric-picker"><legend>Metric</legend><label><span className="sr-only">Search target metrics</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search metrics…"/></label><input type="hidden" name="metric" value={selected}/><div className="target-metric-groups">{targetMetricGroups.map(group=>{const metrics=group.metrics.filter(metric=>!needle||metric.toLowerCase().includes(needle)||group.label.toLowerCase().includes(needle));return metrics.length?<section key={group.label}><h3>{group.label}</h3>{metrics.map(metric=><button className={selected===metric?"selected":""} type="button" aria-pressed={selected===metric} onClick={()=>setSelected(metric)} key={metric}>{metric}</button>)}</section>:null;})}</div>{selected?<p className="field-help">Selected: {selected}</p>:<p className="field-help">Choose one canonical metric.</p>}</fieldset>;
}

function Fields({path,choices,branches}:{path:string;rows:DirectoryRow[];choices:DirectoryRow[];branches:DirectoryRow[]}){
  const branchField=branches.length?<label>Branch<select name="branch_id" required><option value="">Select branch</option>{branches.map(branch=><option value={branch.id} key={branch.id}>{branch.primary}</option>)}</select></label>:null;
  if(path===""||path==="members")return <>{branchField}<MemberNameFields/><div className="form-columns"><label>Email<input name="email" type="email" placeholder="name@email.com" required/></label><label>Phone<input name="phone" type="tel" placeholder="0800 000 0000"/></label></div><DepartmentTags choices={choices}/><p className="field-help">A unique membership code will be Automatically allocated. The member can use this membership-code to sign in.</p></>;
  if(path==="soul-winning")return <>{branchField}<label>Evangelism event<select name="event_id" required><option value="">Select event</option>{choices.map(event=><option value={event.id} key={event.id}>{event.primary}</option>)}</select></label><label>Full name<input name="full_name" required maxLength={160}/></label><div className="form-columns"><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone" type="tel" maxLength={40}/></label></div><div className="form-columns"><label>Location<input name="location" maxLength={160}/></label><label>External evangelist<input name="evangelist_name" maxLength={160}/></label></div></>;
  if(path==="enquiries")return <>{branchField}<div className="form-columns"><label>Category<input name="category" required/></label><label>Priority<select name="priority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label></div><label>Subject<input name="subject" required/></label><label>Message<textarea name="body" rows={7} required/></label></>;
  if(path==="quality-control/queries")return <>{branchField}<AssigneeTags choices={choices}/><div className="form-columns"><label>Category<input name="category" required maxLength={120}/></label><label>Priority<select name="priority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label></div><QueryDates/><label>Subject<input name="subject" required maxLength={240}/></label><label>Details<textarea name="body" rows={6} required maxLength={4000}/></label></>;
  if(path==="follow-ups")return <><div className="channel-grid">{["email","whatsapp","sms","call"].map(channel=><label className="channel-choice" key={channel} aria-disabled={channel!=="email"}><input name="channel" type="radio" value={channel} defaultChecked={channel==="email"} disabled={channel!=="email"}/><span>{channel}{channel!=="email"?" — unavailable":""}</span></label>)}</div>{branchField}<label>Campaign name<input name="name" required/></label><label>Email subject<input name="subject" required/></label><label>Recipient email<input name="destination" type="email" required/></label><label>Message<textarea name="body" rows={5} required/></label><label>Schedule for later<input name="scheduled_at" type="datetime-local"/></label></>;
  if(path==="targets")return <>{branchField}<label>Period<select name="period_type"><option value="event">Event</option><option value="week">Weekly</option><option value="month">Monthly</option><option value="year">Annual</option><option value="day">Daily</option></select></label><TargetMetricSelector/><label>Target title<input name="title" required maxLength={180} placeholder="Membership crosses 1,500"/></label><label>Period or event label<input name="period_label" required maxLength={120} placeholder="Q4 2026 or Annual Conference"/></label><div className="form-columns"><label>Current value<input name="current_value" type="number" min="0" step="any" defaultValue="0"/></label><label>Goal<input name="goal_value" type="number" min="0.01" step="any" required/></label></div><div className="form-columns"><label>Starts<input name="starts_at" type="datetime-local" required/></label><label>Ends<input name="ends_at" type="datetime-local" required/></label></div><label>Progress step<input name="progress_step" type="number" min="0.01" step="any" defaultValue="1"/></label><fieldset><legend>Notifications</legend><label className="check-label"><input type="checkbox" name="notification_channel" value="in_app"/>in app</label><label className="check-label"><input type="checkbox" name="notification_channel" value="email" defaultChecked/>email</label></fieldset><p className="field-help">SMS and WhatsApp remain unavailable until providers are approved.</p></>;
  return null;
}

export function PageAction({path,label,rows,choices=[],branches=[]}:{path:string;label:string;rows:DirectoryRow[];choices?:DirectoryRow[];branches?:DirectoryRow[]}){
  const [open,setOpen]=useState(false);const [exporting,setExporting]=useState(false);const action=actionMap[path];const actionLabel=label.toLowerCase();const isExport=actionLabel.startsWith("export")||actionLabel.startsWith("download");
  useEffect(()=>{if(exporting&&path==="departments"&&posthog.has_opted_in_capturing())posthog.capture("leadership_report_exported",{row_count:rows.length});},[exporting,path,rows.length]);
  if(isExport&&exportPaths.has(path))return <button className="primary-action secondary-page-action" type="button" disabled={exporting} onClick={async()=>{setExporting(true);try{if(path==="members"){const response=await fetch(`/api/members/export${window.location.search}`);if(!response.ok)throw new Error(`Member export failed with status ${response.status}`);const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download="members-export.csv";link.click();URL.revokeObjectURL(url);if(posthog.has_opted_in_capturing())posthog.capture("members_exported",{filtered:Boolean(window.location.search)});}else{const content=exportCsv(path,rows);const url=URL.createObjectURL(new Blob(["\uFEFF",content],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${path||"overview"}-export.csv`;link.click();URL.revokeObjectURL(url);if(path==="analytics"&&posthog.has_opted_in_capturing())posthog.capture("analytics_exported",{row_count:rows.length});}}catch(error){Sentry.captureException(error,{tags:{route:path,action:"csv_export"},extra:{row_count:rows.length}});}finally{setExporting(false);}}}><DownloadSimpleIcon size={17}/>{exporting?"Exporting...":label}</button>;
  if(!action)return <button className="primary-action" type="button" disabled title="This workflow is read-only."><PlusIcon size={17}/>{label}</button>;
  return <><button className="primary-action" type="button" onClick={()=>{if(path===""&&posthog.has_opted_in_capturing())posthog.capture("dashboard_add_member_clicked");setOpen(true);}}><PlusIcon size={17}/>{label}</button>{open&&<ActionDialog path={path} label={label} rows={rows} choices={choices} branches={branches} action={action} onClose={()=>setOpen(false)}/>}</>;
}

function ActionDialog({path,label,rows,choices,branches,action,onClose}:{path:string;label:string;rows:DirectoryRow[];choices:DirectoryRow[];branches:DirectoryRow[];action:FormAction;onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);
  const dialogName=(path||"overview").replaceAll("/","-");
  const titleId=`${dialogName}-action-title`;
  const descriptionId=`${dialogName}-action-description`;
  const [state,formAction,pending]=useActionState(action,{});
  useEffect(()=>{dialog.current?.showModal();},[]);
  useEffect(()=>{if(state.ok&&path!==""&&path!=="members")queueMicrotask(onClose);},[state.ok,path,onClose]);
  useEffect(()=>{if(state.ok&&(path===""||path==="members")&&posthog.has_opted_in_capturing())posthog.capture("member_created");},[state.ok,path]);
  useEffect(()=>{if(state.ok&&path==="soul-winning"&&posthog.has_opted_in_capturing())posthog.capture("soul_created");},[state.ok,path]);
  useEffect(()=>{if(state.ok&&path==="quality-control/queries"&&posthog.has_opted_in_capturing())posthog.capture("qc_query_created");},[state.ok,path]);
  useEffect(()=>{if(path==="quality-control/queries"&&posthog.has_opted_in_capturing())posthog.capture("qc_query_dialog_opened");},[path]);
  useEffect(()=>{if(path==="targets"&&posthog.has_opted_in_capturing())posthog.capture("target_create_opened");},[path]);
  useEffect(()=>{if(state.ok&&path==="targets"&&posthog.has_opted_in_capturing())posthog.capture("target_created");},[state.ok,path]);
  return <dialog className="action-dialog" ref={dialog} aria-labelledby={titleId} aria-describedby={descriptionId} onClose={onClose}><div className="dialog-heading"><div><p className="eyebrow">Dream Team</p><h2 id={titleId}>{label}</h2><p className="sr-only" id={descriptionId}>Complete this form to {label.toLowerCase()}.</p></div><button type="button" onClick={onClose} aria-label="Close dialog"><XIcon size={20}/></button></div><form action={formAction}><div className="dialog-body"><Fields path={path} rows={rows} choices={choices} branches={branches}/>{state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.ok&&state.message&&<p className="form-success success-callout" role="status">{state.message}</p>}</div><div className="dialog-footer"><button type="button" onClick={onClose}>{state.ok?"Close":"Cancel"}</button>{!state.ok&&<button className="primary-action" disabled={pending}>{pending?"Saving...":label}</button>}</div></form></dialog>;
}
