"use client";

import { useActionState, useEffect, useRef, useTransition } from "react";
import { XIcon } from "@phosphor-icons/react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import posthog from "posthog-js";
import type { DirectoryRow, PageData, QualityIssueDetail } from "./queries";
import { transitionQualityIssue } from "./mutations";
import { DashboardPagination } from "./dashboard-pagination";

const capture=(event:string,properties:Record<string,string|number|boolean>)=>{if(posthog.has_opted_in_capturing())posthog.capture(event,properties);};
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,character=>character.toUpperCase());
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"QI";
const age=(value:string)=>{const created=new Date(value);if(Number.isNaN(created.valueOf()))return "—";const hours=Math.max(0,Math.floor((Date.now()-created.valueOf())/3_600_000));if(hours<24)return `${hours}h`;const days=Math.floor(hours/24);return days<30?`${days}d`:`${Math.floor(days/30)}mo`;};
const nextStatus:Record<string,string>={open:"investigating",investigating:"in_progress",in_progress:"resolved"};

function Transition({issue}:{issue:QualityIssueDetail}){
  const [state,action,pending]=useActionState(transitionQualityIssue,{}),router=useRouter(),next=nextStatus[issue.status];
  useEffect(()=>{if(state.ok&&next){capture(next==="resolved"?"qc_issue_resolved":"qc_issue_status_advanced",{issue_id:issue.id,from_status:issue.status,to_status:next});router.replace(`/dashboard/quality-control/issues?selected=${issue.id}`,{scroll:false});}},[state.ok,issue.id,issue.status,next,router]);
  if(!next)return <p className="issue-terminal">This issue has reached its final workflow state.</p>;
  return <form action={action} className="qc-issue-actions"><input type="hidden" name="issue_id" value={issue.id}/><input type="hidden" name="next_status" value={next}/><label>Transition note <span>(optional)</span><textarea name="note" rows={3} maxLength={2000}/></label><button className="primary-action" disabled={pending}>{pending?"Updating…":next==="resolved"?"Mark resolved":`Move to ${label(next)}`}</button>{state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.ok&&<p className="form-success" role="status">{state.message}</p>}</form>;
}

function IssueDialog({issue,onClose}:{issue:QualityIssueDetail;onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();},[]);
  return <dialog className="action-dialog qc-issue-dialog" ref={dialog} aria-labelledby="qc-issue-title" aria-describedby="qc-issue-dialog-description" onClose={onClose}><div className="dialog-heading"><div><p className="eyebrow">Quality-control issue</p><h2 id="qc-issue-title">{issue.title}</h2><p className="sr-only" id="qc-issue-dialog-description">Review the authorised issue record and advance its workflow state.</p></div><button type="button" onClick={()=>dialog.current?.close()} aria-label="Close issue" title="Close issue"><XIcon size={20}/></button></div><div className="record-dialog-body qc-issue-detail"><div className="qc-issue-summary"><div className="identity-cell"><div className="initials">{initials(issue.reporterName)}</div><div><strong>{issue.reporterName}</strong>{issue.reporterEmail&&<span>{issue.reporterEmail}</span>}</div></div><span className={`status-pill status-${issue.status.replaceAll("_","-")}`}>{label(issue.status)}</span></div><dl><div><dt>Area</dt><dd>{issue.area||"Unspecified"}</dd></div><div><dt>Priority</dt><dd><span className={`status-pill priority-${issue.priority}`}>{label(issue.priority)}</span></dd></div><div><dt>Owner</dt><dd>{issue.ownerName||"Unassigned"}</dd></div><div><dt>Age</dt><dd>{age(issue.createdAt)}</dd></div></dl><article className="qc-report-description"><h3>Issue description</h3><p>{issue.description}</p></article><section className="issue-history" aria-label="Status history"><h3>Status history</h3>{issue.history.length?<ol>{issue.history.map((item,index)=><li key={`${item.createdAt}-${index}`}><span>{label(item.fromStatus||"created")} → {label(item.toStatus)}</span><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString("en-NG")}</time></li>)}</ol>:<p>No transitions recorded yet.</p>}</section><Transition issue={issue}/></div></dialog>;
}

export function QualityIssuesDirectory({data}:{data:PageData}){
  const router=useRouter(),pathname=usePathname(),params=useSearchParams(),[pending,startTransition]=useTransition(),triggerLabel=useRef("");
  useEffect(()=>{if(!params.get("selected")&&triggerLabel.current){const selector=`[aria-label="${CSS.escape(triggerLabel.current)}"]`;queueMicrotask(()=>document.querySelector<HTMLElement>(selector)?.focus());}},[params]);
  const open=(row:DirectoryRow,element:HTMLElement)=>{triggerLabel.current=element.getAttribute("aria-label")||`Open issue ${row.primary}`;const next=new URLSearchParams(params.toString());next.set("selected",row.id);capture("qc_issue_opened",{issue_id:row.id,status:row.status,priority:row.details?.priority||"unknown"});startTransition(()=>router.replace(`${pathname}?${next}`,{scroll:false}));};
  const close=()=>{const next=new URLSearchParams(params.toString());next.delete("selected");startTransition(()=>router.replace(`${pathname}?${next}`,{scroll:false}));};
  return <section className="directory-panel qc-issues-panel" aria-busy={pending}><div className="panel-heading"><div><h2>Issue register</h2><p>Open an issue to review its authorised details and workflow.</p></div><span>{data.pagination?.total||0} issues</span></div>{data.rows.length?<><div className="table-scroll" tabIndex={0} aria-label="Scrollable quality-control issues"><table className="data-table qc-issues-table"><thead><tr><th scope="col">Issue</th><th scope="col">Reported by</th><th scope="col">Area</th><th scope="col">Priority</th><th scope="col">Owner</th><th scope="col">Age</th><th scope="col">Status</th></tr></thead><tbody>{data.rows.map(row=><tr className={row.details?.priority==="critical"?"critical-issue":""} key={row.id} tabIndex={0} role="button" aria-label={`Open issue ${row.primary}`} onClick={event=>open(row,event.currentTarget)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open(row,event.currentTarget);}}}><td><strong>{row.primary}</strong><small>QCI-{row.id.slice(0,8).toUpperCase()}</small></td><td><div className="identity-cell"><div className="initials">{initials(row.details?.reporter_name||"")}</div><div><strong>{row.details?.reporter_name||"System report"}</strong>{row.details?.reporter_email&&<span>{row.details.reporter_email}</span>}</div></div></td><td>{row.details?.area||"—"}</td><td><span className={`status-pill priority-${row.details?.priority||"medium"}`}>{label(row.details?.priority||"medium")}</span></td><td>{row.details?.owner_name||"Unassigned"}</td><td>{age(row.details?.created_at||"")}</td><td><span className={`status-pill status-${row.status.replaceAll("_","-")}`}>{label(row.status)}</span></td></tr>)}</tbody></table></div>{data.pagination&&<DashboardPagination {...data.pagination} label="Quality-control issue pages"/>}</>:<div className="empty-state"><h3>No issues found</h3><p>No issues match the current authorised filters.</p></div>}{data.qualityIssue&&<IssueDialog key={`${data.qualityIssue.id}-${data.qualityIssue.updatedAt}`} issue={data.qualityIssue} onClose={close}/>}</section>;
}
