import type { PageData } from "./queries";
import { DashboardPagination } from "./dashboard-pagination";

const date=(value:string|undefined)=>{if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?"—":new Intl.DateTimeFormat("en-NG",{day:"2-digit",month:"short",year:"numeric"}).format(parsed);};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"QA";
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,character=>character.toUpperCase());

export function QualityQueriesDirectory({data}:{data:PageData}){
  return <section className="directory-panel quality-queries-panel"><div className="panel-heading"><div><h2>Assigned queries</h2><p>Queries may be assigned to one or more members.</p></div><span>{data.pagination?.total||0} queries</span></div>{data.rows.length?<><div className="table-scroll" tabIndex={0} aria-label="Scrollable assigned quality-control queries"><table className="data-table quality-queries-table"><thead><tr><th scope="col">Query</th><th scope="col">Assigned members</th><th scope="col">Priority</th><th scope="col">Issued</th><th scope="col">Due</th><th scope="col">Status</th></tr></thead><tbody>{data.rows.map(row=>{const first=row.related?.[0],additional=Math.max(0,(row.related?.length||0)-1);return <tr key={row.id}><td><strong>{row.primary}</strong><small>LCQ-{row.id.slice(0,8).toUpperCase()} · {row.secondary}</small></td><td>{first?<div className="query-assignee"><span className="initials">{initials(first.primary)}</span><span><strong>{first.primary}</strong>{first.secondary&&<small>{first.secondary}</small>}{additional>0&&<small>+{additional} additional {additional===1?"assignee":"assignees"}</small>}</span></div>:<span className="muted-cell">Unassigned</span>}</td><td><span className={`status-pill priority-${row.details?.priority||"medium"}`}>{label(row.details?.priority||"medium")}</span></td><td>{date(row.details?.issued_at)}</td><td>{date(row.details?.due_at)}</td><td><span className={`status-pill status-${row.status.replaceAll("_","-")}`}>{label(row.status)}</span></td></tr>;})}</tbody></table></div>{data.pagination&&<DashboardPagination {...data.pagination} label="Quality-control query pages"/>}</>:<div className="empty-state"><h3>No queries found</h3><p>No queries match the current authorised filters.</p></div>}</section>;
}
