import { createClient } from "@/lib/supabase/server";
import type { SupabaseClient } from "@supabase/supabase-js";
import * as Sentry from "@sentry/nextjs";
import { resolveAdminContext } from "@/lib/permissions/admin-context";

export type DirectoryRow = { id: string; primary: string; secondary: string; status: string; meta: string; details?:Record<string,string>; related?:DirectoryRow[]; metrics?:string[]; sections?:Record<string,DirectoryRow[]>; modules?:Array<{id:string;title:string;description:string;attachments:DirectoryRow[]}>; sessions?:DirectoryRow[] };
export type AnalyticsIndicator={category:string;indicator:string;current:number;previous:number;change:number|null;status:string};
export type AnalyticsDepartment={id:string;name:string;leader:string;memberCount:number;attendanceRate:number};
export type AnalyticsReport={trend:Array<{label:string;value:number}>;departments:AnalyticsDepartment[];indicators:AnalyticsIndicator[]};
export type EnquiryMessage={id:string;body:string;isInternal:boolean;deliveryStatus:string;senderId:string;createdAt:string};
export type EnquiryThread={id:string;branchId:string;subject:string;body:string;category:string;priority:string;status:string;assignedTo:string;senderName:string;senderEmail:string;handlerName:string;createdAt:string;messages:EnquiryMessage[]};
export type QualityReportDetail={id:string;branchId:string;subject:string;description:string;source:string;category:string;priority:string;status:string;assignedTo:string;reporterName:string;reporterEmail:string;handlerName:string;createdAt:string;updatedAt:string;resolvedAt:string};
export type QualityIssueDetail={id:string;branchId:string;title:string;description:string;area:string;priority:string;status:string;ownerId:string;ownerName:string;reporterName:string;reporterEmail:string;createdAt:string;updatedAt:string;resolvedAt:string;history:Array<{fromStatus:string;toStatus:string;changedBy:string;createdAt:string}>};
export type PageData = { metricValues: string[]; metricSupporting?:string[]; rows: DirectoryRow[]; trophies?:DirectoryRow[]; selectedBranch?:string; selectedId?:string; enquiryThread?:EnquiryThread; qualityReport?:QualityReportDetail; qualityIssue?:QualityIssueDetail; academyClass?:DirectoryRow; choices?:DirectoryRow[]; branches?:DirectoryRow[]; sessions?:DirectoryRow[]; attachments?:DirectoryRow[]; leaders?:DirectoryRow[]; visuals?:Array<{title:string;points:Array<{label:string;value:number}>}>; analytics?:AnalyticsReport; pagination?:{page:number;pageSize:number;total:number}; pageTitle?:string; pageDescription?:string; loadError?: string };
type RawRow = Record<string, unknown>;
export type DashboardQueryOptions = { q?:string; status?:string; source?:string; priority?:string; range?:string; period?:string; session?:string; branch?:string; from?:string; to?:string; category?:string; page?:string; selected?:string; filter?:string; sort?:string };

const text = (value: unknown) => typeof value === "string" ? value : value == null ? "" : String(value);
const formattedDate = (value: unknown) => {
  const parsed = typeof value === "string" ? new Date(value) : null;
  return parsed && !Number.isNaN(parsed.valueOf()) ? new Intl.DateTimeFormat("en-NG", { day:"2-digit", month:"short", year:"numeric" }).format(parsed) : "—";
};
const rowStatus = (value: RawRow) => {
  if (value.status != null && text(value.status)) return text(value.status);
  if (typeof value.is_active === "boolean") return value.is_active ? "active" : "inactive";
  if (typeof value.active === "boolean") return value.active ? "active" : "inactive";
  return "unknown";
};
const directoryRow = (value: RawRow, _fallback: string): DirectoryRow => ({
  id: text(value.id || value.department_id || value.event_id),
  primary: text(value.full_name || value.title || value.name || value.subject || value.department_name) || "—",
  secondary: text(value.email || value.category || value.description || value.code || ""),
  status: rowStatus(value),
  meta: formattedDate(value.created_at || value.won_at || value.starts_at || value.event_start_at || value.event_start_date),
  details:Object.fromEntries(Object.entries(value).filter(([,entry])=>["string","number","boolean"].includes(typeof entry)).map(([key,entry])=>[key,text(entry)])),
});
const statusCount = (rows: RawRow[], statuses: string[]) => rows.filter(item => statuses.includes(text(item.status).toLowerCase())).length;
const targetCategory=(metric:string)=>["Total Membership","New Members Joined","Active Members","Member Retention Rate"].includes(metric)?"Membership":["Number of Souls Won","Souls in Follow-up","Souls Integrated","Outreach Campaigns Completed"].includes(metric)?"Souls":["Service Attendance","Event Registrations","Event Attendance Rate","Number of Events Held"].includes(metric)?"Events & Attendance":["Monthly Active Users","App Adoption Rate","Mobile Check-ins","Actions Completed in App"].includes(metric)?"App Usage":"Other";
const targetStatus=(item:RawRow)=>{if(text(item.status).toLowerCase()==="achieved")return"Completed";const current=Number(item.current_value||0),goal=Number(item.goal_value||0),progress=goal?Math.min(1,current/goal):0,start=new Date(text(item.starts_at)).valueOf(),end=new Date(text(item.ends_at)).valueOf(),now=Date.now(),expected=Number.isFinite(start)&&Number.isFinite(end)&&end>start?Math.max(0,Math.min(1,(now-start)/(end-start))):0;if(progress+0.15<expected)return"At risk";if(progress>=expected)return"On track";return"Progressing";};

async function selectRows(table: string, columns = "*", filter?: { column: string; value: string }, options?: { searchColumn?:string; q?:string; status?:string; dateColumn?:string; startAt?:string; endAt?:string; branchId?:string; branchColumn?:string }) {
  const supabase = await createClient();
  // Temporary compatibility boundary for the new migration. Remove after the
  // linked schema is deployed and database.types.ts is regenerated.
  const migrationAwareClient = supabase as unknown as SupabaseClient;
  let query = migrationAwareClient.from(table).select(columns).limit(50);
  if (filter) query = query.eq(filter.column, filter.value);
  if (options?.q && options.searchColumn) query=query.ilike(options.searchColumn,`%${options.q.replaceAll("%","")}%`);
  if (options?.status) query=query.eq("status",options.status);
  if (options?.startAt && options.dateColumn) query=query.gte(options.dateColumn,options.startAt);
  if (options?.endAt && options.dateColumn) query=query.lte(options.dateColumn,options.endAt);
  if (options?.branchId) query=query.eq(options.branchColumn||"branch_id",options.branchId);
  const { data, error } = await query;
  if (error) throw error;
  return (data || []) as unknown as RawRow[];
}

function rangeStart(range:string|undefined){const days:Record<string,number>={today:0,yesterday:1,"7d":7,"30d":30,"3m":90,"6m":180,"12m":365};const value=days[range||"30d"]??30;const result=new Date();result.setUTCDate(result.getUTCDate()-value);result.setUTCHours(0,0,0,0);return result.toISOString();}
function dateBounds(options:DashboardQueryOptions){const custom=options.range==="custom"&&/^\d{4}-\d{2}-\d{2}$/.test(options.from||"")&&/^\d{4}-\d{2}-\d{2}$/.test(options.to||"");const startAt=custom?new Date(`${options.from}T00:00:00.000Z`).toISOString():rangeStart(options.range);const endAt=custom?new Date(`${options.to}T23:59:59.999Z`).toISOString():new Date().toISOString();return{startAt,endAt};}

async function queryDashboardPageData(path: string, options:DashboardQueryOptions={}): Promise<PageData> {
  try {
    if (path === "") {
      const client=await createClient();const rpcClient=client as unknown as SupabaseClient;const {startAt,endAt}=dateBounds(options);
      const overview=await rpcClient.rpc("churchmetric_membership_overview",{p_start_at:startAt,p_end_at:endAt,p_branch_id:options.branch||null});
      if(!overview.error&&overview.data&&typeof overview.data==="object"){
        const metrics=overview.data as RawRow;const total=Number(metrics.total_members||0),active=Number(metrics.active_members||0);
        const departments=Array.isArray(metrics.departments)?metrics.departments as RawRow[]:[];const trend=Array.isArray(metrics.membership_trend)?metrics.membership_trend as RawRow[]:[];const activity=Array.isArray(metrics.recent_activity)?metrics.recent_activity as RawRow[]:[];
        return {metricValues:[String(total),String(active),String(metrics.souls_won||0),String(metrics.new_members||0),String(metrics.open_enquiries||0)],rows:activity.map(item=>directoryRow({...item,full_name:item.member_name,email:item.member_email,status:item.status,created_at:item.created_at,department_name:item.department_name,activity:item.activity,completion_percent:item.completion_percent,href:item.entity_type==="profile"?`/dashboard/members?q=${encodeURIComponent(text(item.member_email||item.member_name))}`:""},"Activity")),visuals:[{title:"Membership over time",points:trend.slice(-8).map(item=>({label:formattedDate(item.label),value:Number(item.value||0)}))},{title:"Members by department",points:departments.slice(0,8).map(item=>({label:text(item.name),value:Number(item.member_count||0)}))}]};
      }
      if(overview.error)throw overview.error;
      return { metricValues:[], rows:[] };
    }
    if (path === "analytics") {
      const client=await createClient();const rpcClient=client as unknown as SupabaseClient;const {startAt,endAt}=dateBounds(options);
      const report=await rpcClient.rpc("churchmetric_analytics_report_v1",{p_start_at:startAt,p_end_at:endAt,p_category:options.category||"all",p_branch_id:options.branch||null});
      if(report.error)throw report.error;
      const payload=(report.data&&typeof report.data==="object"?report.data:{}) as RawRow;const metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow;
      const rawIndicators=Array.isArray(payload.indicators)?payload.indicators as RawRow[]:[];const rawDepartments=Array.isArray(payload.departments)?payload.departments as RawRow[]:[];const rawTrend=Array.isArray(payload.trend)?payload.trend as RawRow[]:[];
      const indicators:AnalyticsIndicator[]=rawIndicators.map(item=>({category:text(item.category),indicator:text(item.indicator),current:Number(item.current_value||0),previous:Number(item.previous_value||0),change:item.change_percent==null?null:Number(item.change_percent),status:text(item.status)}));
      const departments:AnalyticsDepartment[]=rawDepartments.map(item=>({id:text(item.id),name:text(item.name),leader:text(item.leader)||"Unassigned",memberCount:Number(item.member_count||0),attendanceRate:Number(item.attendance_rate||0)}));
      const trend=rawTrend.map(item=>({label:text(item.label),value:Number(item.value||0)}));
      return {metricValues:[String(metrics.total_members||0),`${Number(metrics.active_member_rate||0)}%`,String(metrics.souls_won||0),String(metrics.recorded_attendance||0)],rows:indicators.map((item,index)=>({id:`${item.category}-${index}`,primary:item.indicator,secondary:item.category,status:item.status,meta:String(item.current),details:{current:String(item.current),previous:String(item.previous),change:item.change==null?"New":`${item.change}%`}})),analytics:{trend,departments,indicators}};
    }
    if (path === "events") {
      const client=await createClient();const rpcClient=client as unknown as SupabaseClient;const {startAt,endAt}=dateBounds(options);
      const page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const report=await rpcClient.rpc("churchmetric_events_report_v1",{p_start_at:startAt,p_end_at:endAt,p_search:(options.q||"").trim().slice(0,100),p_branch_id:options.branch||null,p_page:page,p_page_size:pageSize});
      if(report.error)throw report.error;
      const payload=(report.data&&typeof report.data==="object"?report.data:{}) as RawRow;const metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow;const events=Array.isArray(payload.events)?payload.events as RawRow[]:[];
      return {metricValues:[String(metrics.total_events||0),String(metrics.total_attendance||0),String(metrics.average_attendance||0),formattedDate(metrics.latest_event)],pagination:{page,pageSize:Number(payload.page_size||pageSize),total:Number(payload.total||0)},rows:events.map(event=>directoryRow({...event,id:event.id,created_at:event.event_start_date,status:event.is_active,attendance_count:event.attendance_count},"Event"))};
    }
    if (path === "departments") {
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,{data,error}=await rpcClient.rpc("churchmetric_departments_report_v1",{p_search:(options.q||"").trim().slice(0,100),p_branch_id:options.branch||null});if(error)throw error;const payload=(data&&typeof data==="object"?data:{}) as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow,departments=Array.isArray(payload.departments)?payload.departments as RawRow[]:[];
      return {metricValues:[String(metrics.departments||0),String(metrics.assigned_members||0),String(metrics.department_leaders||0),`${Number(metrics.average_attendance||0)}%`],rows:departments.map(v=>directoryRow({...v,id:v.id,name:v.name,created_at:null},"Department"))};
    }
    if (path.startsWith("departments/")) {
      const departmentId=path.split("/")[1],client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const {data,error}=await rpcClient.rpc("churchmetric_department_detail_v1",{p_department_id:departmentId,p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100),p_page:page,p_page_size:pageSize});if(error)throw error;
      const payload=(data&&typeof data==="object"?data:{}) as RawRow,department=(payload.department&&typeof payload.department==="object"?payload.department:{}) as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow,members=Array.isArray(payload.members)?payload.members as RawRow[]:[],leaders=Array.isArray(payload.leaders)?payload.leaders as RawRow[]:[],attachments=Array.isArray(payload.attachments)?payload.attachments as RawRow[]:[];
      return {selectedBranch:text(payload.branch_id),pageTitle:text(department.name)||"Department details",pageDescription:text(department.description)||"Review department membership, leadership and attendance performance.",metricValues:[String(metrics.total_members||0),String(metrics.active_members||0),String(metrics.department_leaders||0),`${Number(metrics.attendance_rate||0)}%`],pagination:{page,pageSize:Number(payload.page_size||pageSize),total:Number(payload.members_total||0)},rows:members.map(v=>directoryRow({...v,status:v.verified?"active":"inactive",created_at:v.date_joined||v.created_at},"Member")),attachments:attachments.map(v=>directoryRow({...v,title:v.file_name,status:v.mime_type},"Attachment")),leaders:leaders.map(v=>directoryRow({...v,full_name:v.full_name,email:v.email,status:v.is_active?"active":"inactive",title:v.title_name,created_at:v.start_date},"Leader"))};
    }
    if(path==="soul-winning"){
      const client=await createClient();const rpcClient=client as unknown as SupabaseClient;const {startAt,endAt}=dateBounds(options);const page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const [report,choiceResult]=await Promise.all([rpcClient.rpc("churchmetric_soul_winning_report_v1",{p_start_at:startAt,p_end_at:endAt,p_search:(options.q||"").trim().slice(0,100),p_branch_id:options.branch||null,p_page:page,p_page_size:pageSize}),rpcClient.from("evangelism_events").select("id,title,branch_id,starts_at").order("starts_at",{ascending:false}).limit(500)]);
      if(report.error)throw report.error;if(choiceResult.error)throw choiceResult.error;const payload=(report.data&&typeof report.data==="object"?report.data:{}) as RawRow;const metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow;const events=Array.isArray(payload.events)?payload.events as RawRow[]:[];
      return {metricValues:[String(metrics.souls_won||0),String(metrics.contacted||0),String(metrics.integrated||0),String(metrics.awaiting_contact||0)],pagination:{page,pageSize:Number(payload.page_size||pageSize),total:Number(payload.total||0)},rows:events.map(event=>directoryRow({...event,created_at:event.starts_at},"Evangelism event")),choices:((choiceResult.data||[]) as RawRow[]).map(event=>directoryRow({...event,created_at:event.starts_at},"Evangelism event"))};
    }
    if(path==="enquiries"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const inbox=await rpcClient.rpc("churchmetric_enquiries_inbox_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});
      if(inbox.error)throw inbox.error;
      const payload=(inbox.data&&typeof inbox.data==="object"?inbox.data:{}) as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],handlers=Array.isArray(payload.handlers)?payload.handlers as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{}) as RawRow;
      const selectedId=(options.selected||items[0]?.id||"").toString();let enquiryThread:EnquiryThread|undefined;
      if(selectedId){const thread=await rpcClient.rpc("churchmetric_enquiry_thread_v1",{p_enquiry_id:selectedId});if(thread.error)throw thread.error;const value=(thread.data&&typeof thread.data==="object"?thread.data:{}) as RawRow;const messages=Array.isArray(value.messages)?value.messages as RawRow[]:[];enquiryThread={id:text(value.id),branchId:text(value.branch_id),subject:text(value.subject),body:text(value.body),category:text(value.category),priority:text(value.priority),status:text(value.status),assignedTo:text(value.assigned_to),senderName:text(value.sender_name)||"—",senderEmail:text(value.sender_email),handlerName:text(value.handler_name),createdAt:text(value.created_at),messages:messages.map(message=>({id:text(message.id),body:text(message.body),isInternal:Boolean(message.is_internal),deliveryStatus:text(message.delivery_status),senderId:text(message.sender_id),createdAt:text(message.created_at)}))};}
      return {metricValues:[String(metrics.open||0),String(metrics.in_progress||0),String(metrics.closed||0),String(metrics.overdue||0)],selectedId,enquiryThread,pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},choices:handlers.map(handler=>directoryRow({...handler,id:handler.id,full_name:handler.name,status:"active"},"Handler")),rows:items.map(item=>directoryRow({...item,id:item.id,full_name:item.sender_name,email:item.sender_email,created_at:item.created_at,status:item.status,subject:item.subject},"Enquiry"))};
    }
    if(path==="quality-control/reports"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const inbox=await rpcClient.rpc("churchmetric_quality_reports_inbox_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_source:options.source||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});if(inbox.error)throw inbox.error;
      const payload=(inbox.data&&typeof inbox.data==="object"?inbox.data:{}) as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],handlers=Array.isArray(payload.handlers)?payload.handlers as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{}) as RawRow;
      const selectedId=(options.selected||"").toString();let qualityReport:QualityReportDetail|undefined;if(selectedId){const detail=await rpcClient.rpc("churchmetric_quality_report_detail_v1",{p_report_id:selectedId});if(detail.error)throw detail.error;const value=(detail.data&&typeof detail.data==="object"?detail.data:{}) as RawRow;if(value.id)qualityReport={id:text(value.id),branchId:text(value.branch_id),subject:text(value.subject),description:text(value.description),source:text(value.source),category:text(value.category),priority:text(value.priority),status:text(value.status),assignedTo:text(value.assigned_to),reporterName:text(value.reporter_name)||"Unknown reporter",reporterEmail:text(value.reporter_email),handlerName:text(value.handler_name),createdAt:text(value.created_at),updatedAt:text(value.updated_at),resolvedAt:text(value.resolved_at)};}
      const averageHours=Number(metrics.average_resolution_hours||0),averageResolution=averageHours>=24?`${(averageHours/24).toFixed(1)}d`:`${averageHours.toFixed(1)}h`;
      return {metricValues:[String(metrics.open_reports||0),String(metrics.active_queries||0),String(metrics.open_issues||0),averageResolution],selectedId,qualityReport,pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},choices:handlers.map(handler=>directoryRow({...handler,full_name:handler.name,status:"active"},"Handler")),rows:items.map(item=>directoryRow({...item,full_name:item.reporter_name,email:item.reporter_email,created_at:item.created_at},"Report"))};
    }
    if(path==="quality-control/queries"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const result=await rpcClient.rpc("churchmetric_quality_queries_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{}) as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{}) as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],members=Array.isArray(payload.members)?payload.members as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{}) as RawRow;
      return {metricValues:[String(metrics.open||0),String(metrics.awaiting_response||0),String(metrics.overdue||0),String(metrics.responded||0)],pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},rows:items.map(item=>{const assignees=Array.isArray(item.assignees)?item.assignees as RawRow[]:[];return {...directoryRow({...item,title:item.subject,created_at:item.issued_at,status:item.overdue?"overdue":item.status},"Query"),related:assignees.map(assignee=>directoryRow({...assignee,full_name:assignee.name,status:assignee.responded_at?"responded":"awaiting_response"},"Assignee"))};}),choices:members.map(member=>directoryRow({...member,full_name:member.name,status:"active"},"Member"))};
    }
    if(path==="quality-control/issues"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25,result=await rpcClient.rpc("churchmetric_quality_issues_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_priority:options.priority||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow,selectedId=(options.selected||"").toString();let qualityIssue:QualityIssueDetail|undefined;
      if(selectedId){const detail=await rpcClient.rpc("churchmetric_quality_issue_detail_v1",{p_issue_id:selectedId});if(detail.error)throw detail.error;const value=(detail.data&&typeof detail.data==="object"?detail.data:{})as RawRow,history=Array.isArray(value.history)?value.history as RawRow[]:[];if(value.id)qualityIssue={id:text(value.id),branchId:text(value.branch_id),title:text(value.title),description:text(value.description),area:text(value.area),priority:text(value.priority),status:text(value.status),ownerId:text(value.owner_id),ownerName:text(value.owner_name),reporterName:text(value.reporter_name)||"System report",reporterEmail:text(value.reporter_email),createdAt:text(value.created_at),updatedAt:text(value.updated_at),resolvedAt:text(value.resolved_at),history:history.map(item=>({fromStatus:text(item.from_status),toStatus:text(item.to_status),changedBy:text(item.changed_by),createdAt:text(item.created_at)}))};}
      return {metricValues:[String(metrics.open||0),String(metrics.critical||0),String(metrics.in_progress||0),String(metrics.resolved||0)],selectedId,qualityIssue,pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},rows:items.map(item=>directoryRow({...item,full_name:item.reporter_name,email:item.reporter_email,created_at:item.created_at},"Issue"))};
    }
    if(path==="follow-ups"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const result=await rpcClient.rpc("churchmetric_followups_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow;
      return {metricValues:[String(metrics.campaigns_sent||0),String(metrics.recipients_reached||0),`${Number(metrics.delivery_rate||0)}%`,String(metrics.calls_pending||0)],pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},rows:items.map(item=>directoryRow({...item,category:item.audience_category,completed_recipients:item.completed_recipients,total_recipients:item.total_recipients,failed_recipients:item.failed_recipients},"Campaign"))};
    }
    if(path==="members"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const [result,departmentResult]=await Promise.all([rpcClient.rpc("churchmetric_members_report_v3",{p_search:(options.q||"").trim().slice(0,100),p_status:options.status||null,p_filter:options.filter||null,p_sort:options.sort||"newest",p_branch_id:options.branch||null,p_page:page,p_page_size:pageSize}),selectRows("departments","id,name")]);if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow;
      return{metricValues:[String(metrics.total||0),String(metrics.active||0),String(metrics.new_this_month||0),String(metrics.inactive||0)],pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},choices:departmentResult.map(item=>directoryRow(item,"Department")),rows:items.map(item=>directoryRow({...item,created_at:item.date_joined||item.created_at,status:item.is_active?"active":"inactive"},"Member"))};
    }
    if(path==="academy/classes"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25;
      const result=await rpcClient.rpc("churchmetric_academy_classes_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow,selectedId=(options.selected||"").toString();let academyClass:DirectoryRow|undefined;
      if(selectedId){const detail=await rpcClient.rpc("churchmetric_academy_class_detail_v1",{p_course_id:selectedId,p_session_id:options.session||null});if(detail.error)throw detail.error;const value=(detail.data&&typeof detail.data==="object"?detail.data:{})as RawRow,course=(value.course&&typeof value.course==="object"?value.course:{})as RawRow,detailMetrics=(value.metrics&&typeof value.metrics==="object"?value.metrics:{})as RawRow,modules=Array.isArray(value.modules)?value.modules as RawRow[]:[],sessions=Array.isArray(value.sessions)?value.sessions as RawRow[]:[],students=Array.isArray(value.students)?value.students as RawRow[]:[];academyClass={...directoryRow({...course,created_at:null},"Class"),secondary:text(course.description),metrics:[String(detailMetrics.modules||0),String(detailMetrics.attachments||0),String(detailMetrics.students||0),String(detailMetrics.sessions||0),`${Number(detailMetrics.completion||0)}%`],modules:modules.map(module=>{const files=Array.isArray(module.attachments)?module.attachments as RawRow[]:[];return{id:text(module.id),title:text(module.title),description:text(module.description),attachments:files.map(file=>directoryRow({...file,title:file.file_name,status:file.mime_type},"Attachment"))};}),sessions:sessions.map(session=>directoryRow({...session,created_at:session.starts_at},"Session")),related:students.map(student=>directoryRow({...student,full_name:student.name,email:student.email,status:student.status,progress_percent:student.progress,department_name:student.department},"Student"))};}
      return{metricValues:[String(metrics.active_classes||0),String(metrics.enrolled_members||0),String(metrics.instructors||0),`${Number(metrics.completion_rate||0)}%`,String(metrics.yet_to_attend||0)],selectedId,academyClass,pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},rows:items.map(item=>directoryRow({...item,created_at:item.created_at},"Class"))};
    }
    if(path==="academy/enrolments"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25,result=await rpcClient.rpc("churchmetric_academy_enrolments_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_filter:options.status||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow;
      return{metricValues:[String(metrics.total||0),String(metrics.in_progress||0),String(metrics.completed||0),String(metrics.yet_to_attend||0)],pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},rows:items.map(item=>directoryRow({...item,full_name:item.member_name,email:item.member_email,status:item.display_status,created_at:item.updated_at},"Enrolment"))};
    }
    if(path==="academy/instructors"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25,result=await rpcClient.rpc("churchmetric_academy_instructors_v1",{p_branch_id:options.branch||null,p_session_id:options.session||null,p_search:(options.q||"").trim().slice(0,100)||null,p_status:options.status||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,metrics=(payload.metrics&&typeof payload.metrics==="object"?payload.metrics:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],rawSessions=Array.isArray(payload.sessions)?payload.sessions as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow;
      return{pageDescription:`Manage facilitators and their class assignments. ${text(payload.weighting)}`,metricValues:[String(metrics.instructors_in_session||0),String(metrics.active_instructors||0),String(metrics.classes_assigned||0),`${Number(metrics.average_completion||0)}%`],sessions:rawSessions.map(item=>directoryRow({...item,created_at:item.starts_at},"Session")),pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:Number(pagination.total||0)},rows:items.map(item=>{const classes=Array.isArray(item.classes)?item.classes as RawRow[]:[];return{...directoryRow({...item,status:item.active?"active":"inactive",category:item.bio,unique_learners:item.unique_learners,weighted_completion:item.weighted_completion},"Instructor"),related:classes.map(value=>directoryRow({...value,status:"assigned"},"Class"))};})};
    }
    if(path.startsWith("academy/")){
      const [courses,enrolments,instructors,assignments,profiles,sessions]=await Promise.all([selectRows("courses","*"),selectRows("course_enrollments","*"),selectRows("academy_instructors","*"),selectRows("academy_instructor_assignments","*"),selectRows("profiles","id,full_name,email,membership_code"),selectRows("academy_sessions","id,title,course_id,status,starts_at")]);const profilesById=new Map(profiles.map(profile=>[text(profile.id),profile]));const coursesById=new Map(courses.map(course=>[text(course.id),course]));
      const academyNeedle=(options.q||"").trim().toLowerCase();
      const scopedAssignments=options.session?assignments.filter(item=>text(item.session_id)===options.session):assignments;const instructorIds=new Set(scopedAssignments.map(item=>text(item.instructor_id)));const scopedInstructors=options.session?instructors.filter(item=>instructorIds.has(text(item.id))):instructors;const scopedCourseIds=new Set(scopedAssignments.map(item=>text(item.course_id)));const scopedEnrolments=options.session?enrolments.filter(item=>scopedCourseIds.has(text(item.course_id))):enrolments;const scopedCompleted=scopedEnrolments.reduce((sum,item)=>sum+Number(item.progress_percent||0),0);
      return {sessions:sessions.map(item=>directoryRow(item,"Session")),metricValues:[String(scopedInstructors.length),String(scopedInstructors.filter(item=>item.active===true).length),String(new Set(scopedAssignments.map(item=>text(item.course_id))).size),scopedEnrolments.length?`${Math.round(scopedCompleted/scopedEnrolments.length)}%`:"0%"],rows:scopedInstructors.filter(item=>{const profile=profilesById.get(text(item.profile_id)),instructorAssignments=scopedAssignments.filter(assignment=>text(assignment.instructor_id)===text(item.id));return (!options.status||(item.active?"active":"inactive")===options.status)&&(!academyNeedle||[profile?.full_name,profile?.email,item.bio,...instructorAssignments.map(assignment=>coursesById.get(text(assignment.course_id))?.title)].some(value=>text(value).toLowerCase().includes(academyNeedle)));}).map(item=>{const profile=profilesById.get(text(item.profile_id));const instructorAssignments=scopedAssignments.filter(assignment=>text(assignment.instructor_id)===text(item.id));const courseIds=new Set(instructorAssignments.map(assignment=>text(assignment.course_id)));const instructorEnrolments=scopedEnrolments.filter(enrolment=>courseIds.has(text(enrolment.course_id)));return directoryRow({...item,full_name:profile?.full_name||"—",email:profile?.email||"",status:item.active?"active":"inactive",category:`${courseIds.size} classes`,unique_learners:new Set(instructorEnrolments.map(enrolment=>text(enrolment.user_id))).size,weighted_completion:instructorEnrolments.length?`${Math.round(instructorEnrolments.reduce((sum,enrolment)=>sum+Number(enrolment.progress_percent||0),0)/instructorEnrolments.length)}%`:"0%"},"Instructor");})};
    }
    if(path==="targets"||path==="awards"){
      const client=await createClient(),rpcClient=client as unknown as SupabaseClient,page=Math.max(1,Number.parseInt(options.page||"1",10)||1),pageSize=25,result=await rpcClient.rpc("churchmetric_targets_v1",{p_branch_id:options.branch||null,p_search:(options.q||"").trim().slice(0,100)||null,p_period:options.period||null,p_page:page,p_page_size:pageSize});if(result.error)throw result.error;
      const payload=(result.data&&typeof result.data==="object"?result.data:{})as RawRow,items=Array.isArray(payload.items)?payload.items as RawRow[]:[],rawTrophies=Array.isArray(payload.trophies)?payload.trophies as RawRow[]:[],pagination=(payload.pagination&&typeof payload.pagination==="object"?payload.pagination:{})as RawRow;
      if(path==="awards"){const awards=rawTrophies.map(item=>{const metric=text(item.metric),periodLabel=text(item.period_label)||text(item.period_type);return directoryRow({...item,description:metric,status:"earned",created_at:item.achieved_at,period_label:periodLabel},"Award");}).filter(item=>(!options.q||[item.primary,item.secondary,item.details?.metric].some(value=>text(value).toLowerCase().includes((options.q||"").trim().toLowerCase())))&&(!options.period||item.details?.period_type===options.period));const now=new Date(),quarterStart=new Date(Date.UTC(now.getUTCFullYear(),Math.floor(now.getUTCMonth()/3)*3,1)),periodCount=new Set(awards.map(item=>item.details?.period_label).filter(Boolean)).size;return{metricValues:[String(awards.length),String(awards.filter(item=>new Date(item.details?.achieved_at||0)>=quarterStart).length),String(periodCount),awards[0]?.primary||"—"],metricSupporting:["Recorded achievements",`Q${Math.floor(now.getUTCMonth()/3)+1} ${now.getUTCFullYear()}`,"Distinct achievement periods",awards[0]?.meta?`Achieved ${awards[0].meta}`:"No awards yet"],rows:awards};}
      const targetRows=items.map(item=>{const status=targetStatus(item),category=targetCategory(text(item.metric));return directoryRow({...item,status,category},"Target");}).filter(item=>(!options.category||options.category==="all"||item.details?.category===options.category)&&(!options.status||item.status.toLowerCase().replaceAll(" ","-")===options.status));const onTrack=targetRows.filter(item=>item.status==="On track").length,atRisk=targetRows.filter(item=>item.status==="At risk").length,active=Number(pagination.total||targetRows.length);return {metricValues:[String(active),String(onTrack),String(rawTrophies.length),String(atRisk)],metricSupporting:["Across all target categories",active?`${Math.round(onTrack*100/active)}% of active targets`:"No active targets","This year","Require attention"],trophies:rawTrophies.map(item=>directoryRow({...item,created_at:item.achieved_at,category:item.period_label},"Trophy")),pagination:{page:Number(pagination.page||page),pageSize:Number(pagination.page_size||pageSize),total:targetRows.length},rows:targetRows};
    }
    const tableMap: Record<string,string> = { targets:"targets" };
    const table=tableMap[path];
    if (!table) return {metricValues:[],rows:[]};
    const searchColumn:Record<string,string>={profiles:"full_name",souls:"full_name",enquiries:"subject",quality_reports:"subject",quality_queries:"subject",quality_issues:"title",courses:"title",broadcast_campaigns:"name",targets:"title"};
    const rows=await selectRows(table,"*",undefined,{q:options.q,searchColumn:searchColumn[table],status:options.status});
    const active=statusCount(rows,["active","open","in_progress","dispatching","scheduled"]);
    const completed=statusCount(rows,["completed","resolved","sent","achieved","closed"]);
    const pending=statusCount(rows,["pending","not_started","awaiting_contact","awaiting_response","draft"]);
    return {metricValues:[String(rows.length),String(active),String(completed),String(pending),"—"],rows:rows.map(v=>directoryRow(v,table.replaceAll("_"," ")))};
  } catch (error) {
    Sentry.captureException(error,{tags:{route:path||"overview",action:"dashboard_page_query"}});
    console.error("dashboard_page_query_failed", { path, code: typeof error === "object" && error && "code" in error ? String(error.code) : "unknown" });
    return { metricValues:[], rows:[], loadError:"The authorised data could not be loaded. Try again after the database migration is deployed." };
  }
}

export async function loadDashboardPageData(path:string,options:DashboardQueryOptions={}):Promise<PageData>{
  return Sentry.startSpan({name:"dashboard.page_data",op:"db.query",attributes:{route:path||"overview",period:options.range||"30d",category:options.category||"all",branch_id:options.branch||"authorised"}},async(span)=>{const data=await queryDashboardPageData(path,options);span.setAttribute("row_count",data.rows.length);try{const client=await createClient();const context=await resolveAdminContext(client as unknown as SupabaseClient);if(context?.role==="globaladmin"){const rows=await selectRows("branches","id,name,slug");data.branches=rows.map(item=>directoryRow(item,"Branch"));}}catch{}return data;});
}
