"use client";

import { useActionState } from "react";
import { addTargetProgress, transitionQualityIssue, transitionQualityReport, transitionSoul } from "./mutations";
import type { DirectoryRow } from "./queries";

function TargetProgress({row}:{row:DirectoryRow}){const [state,action,pending]=useActionState(addTargetProgress,{});return <form action={action} className="record-action-form"><input type="hidden" name="target_id" value={row.id}/><label>Add progress<input name="delta" type="number" step="any" required/></label><button className="primary-action" disabled={pending}>{pending?"Updating…":"Update progress"}</button>{state.error&&<p className="form-error">{state.error}</p>}{state.ok&&<p className="form-success">Progress updated.</p>}</form>;}
function IssueTransition({row}:{row:DirectoryRow}){const next:Record<string,string>={open:"investigating",investigating:"in_progress",in_progress:"resolved",resolved:"closed"};const value=next[row.status.toLowerCase()];const [state,action,pending]=useActionState(transitionQualityIssue,{});if(!value)return null;return <form action={action} className="record-action-form"><input type="hidden" name="issue_id" value={row.id}/><input type="hidden" name="next_status" value={value}/><label>Transition note<textarea name="note" rows={3}/></label><button className="primary-action" disabled={pending}>{pending?"Updating…":`Move to ${value.replaceAll("_"," ")}`}</button>{state.error&&<p className="form-error">{state.error}</p>}{state.ok&&<p className="form-success">Issue status updated.</p>}</form>;}
function ReportTransition({row}:{row:DirectoryRow}){const [state,action,pending]=useActionState(transitionQualityReport,{});if(["resolved","closed"].includes(row.status.toLowerCase()))return null;return <form action={action} className="record-action-form report-actions"><input type="hidden" name="report_id" value={row.id}/><button name="report_action" value="escalate" className="secondary-action" disabled={pending}>Escalate to issue</button><button name="report_action" value="resolve" className="primary-action" disabled={pending}>Mark resolved</button>{state.error&&<p className="form-error">{state.error}</p>}{state.ok&&<p className="form-success">Report updated.</p>}</form>;}
function SoulTransition({row}:{row:DirectoryRow}){const next:Record<string,string>={awaiting_contact:"contacted",contacted:"integrating",integrating:"integrated"};const value=next[row.status.toLowerCase()];const [state,action,pending]=useActionState(transitionSoul,{});if(!value)return null;return <form action={action} className="record-action-form"><input type="hidden" name="soul_id" value={row.id}/><input type="hidden" name="next_status" value={value}/><label>Follow-up notes<textarea name="notes" rows={3}/></label><button className="primary-action" disabled={pending}>{pending?"Updating…":`Move to ${value.replaceAll("_"," ")}`}</button>{state.error&&<p className="form-error">{state.error}</p>}{state.ok&&<p className="form-success">Follow-up status updated.</p>}</form>;}
export function RecordActions({path,row}:{path:string;row:DirectoryRow}){if(path==="targets")return <TargetProgress row={row}/>;if(path==="quality-control/issues")return <IssueTransition row={row}/>;if(path==="quality-control/reports")return <ReportTransition row={row}/>;if(path==="soul")return <SoulTransition row={row}/>;return null;}
