"use client";
import { XIcon } from "@phosphor-icons/react";
import posthog from "posthog-js";
import { useRef, useState } from "react";
import type { DirectoryRow,PageData } from "./queries";
import { EventSoulsDetail } from "./event-souls-detail";
import { DashboardPagination } from "./dashboard-pagination";
const date=(value:string|undefined)=>{if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?"—":parsed.toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"});};
function Identity({row}:{row:DirectoryRow}){return <div className="identity-cell"><div className="initials">{row.primary.split(/\s+/).slice(0,2).map(word=>word[0]).join("").toUpperCase()}</div><div><strong>{row.primary}</strong>{row.secondary&&<span>{row.secondary}</span>}</div></div>;}
export function SoulWinningDirectory({data}:{data:PageData}){const [selected,setSelected]=useState<DirectoryRow|null>(null),dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLElement|null>(null);const open=(row:DirectoryRow,element:HTMLElement)=>{trigger.current=element;setSelected(row);if(posthog.has_opted_in_capturing())posthog.capture("evangelism_event_opened",{event_id:row.id});queueMicrotask(()=>dialog.current?.showModal());};const closed=()=>{setSelected(null);queueMicrotask(()=>trigger.current?.focus());};return <section className="directory-panel"><div className="panel-heading"><div><h2>Soul-winning register</h2><p>Select an event to open its complete souls directory.</p></div></div>{data.loadError?<div className="empty-state error-state-inline" role="alert"><h3>Data unavailable</h3><p>{data.loadError}</p></div>:data.rows.length?<><div className="table-scroll" tabIndex={0} aria-label="Scrollable evangelism event directory"><table className="data-table soul-events-table"><thead><tr><th scope="col">Event</th><th scope="col">Date</th><th scope="col">Venue</th><th scope="col">Team lead</th><th scope="col">Souls won</th><th scope="col">Integrated</th><th scope="col" aria-label="Action"></th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id} tabIndex={0} role="button" aria-label={`Open ${row.primary} souls directory`} onClick={event=>open(row,event.currentTarget)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open(row,event.currentTarget);}}}><td><Identity row={row}/></td><td>{date(row.details?.starts_at)}</td><td>{row.details?.location||"—"}</td><td>{row.details?.team_lead||"Unassigned"}</td><td>{row.details?.souls_won||"0"}</td><td>{row.details?.integrated||"0"}</td><td><button type="button" className="row-link" onClick={event=>{event.stopPropagation();open(row,event.currentTarget);}}>Open directory →</button></td></tr>)}</tbody></table></div>{data.pagination&&<DashboardPagination {...data.pagination} label="Evangelism event directory pages"/>}</>:<div className="empty-state"><h3>No evangelism events found</h3><p>No events match this authorised period and search.</p></div>}<dialog className="action-dialog record-dialog" ref={dialog} aria-labelledby="soul-event-title" aria-describedby="soul-event-description" onClose={closed}>{selected&&<><div className="dialog-heading"><div><p className="eyebrow">Souls directory</p><h2 id="soul-event-title">{selected.primary}</h2><p className="sr-only" id="soul-event-description">Review and update souls attached to this evangelism event.</p></div><button type="button" onClick={()=>dialog.current?.close()} aria-label="Close souls directory" title="Close souls directory"><XIcon size={20}/></button></div><div className="record-dialog-body"><EventSoulsDetail eventId={selected.id}/></div></>}</dialog></section>;}
