create or replace function public.churchmetric_academy_instructors_v1(p_branch_id uuid default null,p_session_id uuid default null,p_search text default null,p_status text default null,p_page integer default 1,p_page_size integer default 25)
returns jsonb language plpgsql security invoker set search_path='' stable as $$
declare v_page integer:=greatest(coalesce(p_page,1),1);v_size integer:=least(greatest(coalesce(p_page_size,25),1),100);v_search text:=nullif(btrim(coalesce(p_search,'')),'');v_total bigint;v_items jsonb;v_metrics jsonb;v_sessions jsonb;
begin
 if p_branch_id is not null and not public.churchmetric_can_manage_branch(p_branch_id)then raise exception 'not_authorized' using errcode='42501';end if;
 if p_status is not null and p_status not in('active','inactive')then raise exception 'invalid_status' using errcode='22023';end if;
 if p_session_id is not null and not exists(select 1 from public.academy_sessions s where s.id=p_session_id and(p_branch_id is null or s.branch_id=p_branch_id))then raise exception 'session_not_found' using errcode='22023';end if;
 with scoped as(
  select ai.id,ai.branch_id,ai.active,ai.bio,p.full_name,p.email,
   coalesce((select jsonb_agg(distinct jsonb_build_object('id',c.id,'title',c.title,'code',c.code))from public.academy_instructor_assignments a join public.courses c on c.id=a.course_id where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id)),'[]'::jsonb)classes,
   (select count(distinct e.user_id)from public.course_enrollments e where(p_session_id is null or e.session_id=p_session_id)and e.course_id in(select a.course_id from public.academy_instructor_assignments a where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id)))unique_learners,
   coalesce((select round(avg(e.progress_percent))from public.course_enrollments e where(p_session_id is null or e.session_id=p_session_id)and e.course_id in(select a.course_id from public.academy_instructor_assignments a where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id))),0)weighted_completion
  from public.academy_instructors ai join public.profiles p on p.id=ai.profile_id where(p_branch_id is null or ai.branch_id=p_branch_id)and(p_status is null or(ai.active and p_status='active')or(not ai.active and p_status='inactive'))and exists(select 1 from public.academy_instructor_assignments a where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id))
 ),filtered as(select * from scoped where v_search is null or full_name ilike '%'||v_search||'%' or email ilike '%'||v_search||'%' or bio ilike '%'||v_search||'%' or exists(select 1 from jsonb_array_elements(classes)x where x->>'title'ilike'%'||v_search||'%'))
 select count(*)into v_total from filtered;
 with scoped as(
  select ai.id,ai.branch_id,ai.active,ai.bio,p.full_name,p.email,
   coalesce((select jsonb_agg(distinct jsonb_build_object('id',c.id,'title',c.title,'code',c.code))from public.academy_instructor_assignments a join public.courses c on c.id=a.course_id where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id)),'[]'::jsonb)classes,
   (select count(distinct e.user_id)from public.course_enrollments e where(p_session_id is null or e.session_id=p_session_id)and e.course_id in(select a.course_id from public.academy_instructor_assignments a where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id)))unique_learners,
   coalesce((select round(avg(e.progress_percent))from public.course_enrollments e where(p_session_id is null or e.session_id=p_session_id)and e.course_id in(select a.course_id from public.academy_instructor_assignments a where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id))),0)weighted_completion
  from public.academy_instructors ai join public.profiles p on p.id=ai.profile_id where(p_branch_id is null or ai.branch_id=p_branch_id)and(p_status is null or(ai.active and p_status='active')or(not ai.active and p_status='inactive'))and exists(select 1 from public.academy_instructor_assignments a where a.instructor_id=ai.id and(p_session_id is null or a.session_id=p_session_id))
 ),filtered as(select * from scoped where v_search is null or full_name ilike '%'||v_search||'%' or email ilike '%'||v_search||'%' or bio ilike '%'||v_search||'%' or exists(select 1 from jsonb_array_elements(classes)x where x->>'title'ilike'%'||v_search||'%'))
 select coalesce(jsonb_agg(to_jsonb(item)order by item.full_name),'[]'::jsonb)into v_items from(select * from filtered order by full_name offset(v_page-1)*v_size limit v_size)item;
 -- Completion is weighted by enrolment rows: each learner-class enrolment contributes one equally weighted progress value.
 with selected_assignments as(select distinct a.instructor_id,a.course_id from public.academy_instructor_assignments a where(p_session_id is null or a.session_id=p_session_id)and(p_branch_id is null or a.branch_id=p_branch_id)),selected_enrolments as(select e.* from public.course_enrollments e where(p_session_id is null or e.session_id=p_session_id)and e.course_id in(select course_id from selected_assignments))
 select jsonb_build_object('instructors_in_session',(select count(distinct instructor_id)from selected_assignments),'active_instructors',(select count(distinct ai.id)from public.academy_instructors ai join selected_assignments a on a.instructor_id=ai.id where ai.active),'classes_assigned',(select count(distinct course_id)from selected_assignments),'average_completion',coalesce((select round(avg(progress_percent))from selected_enrolments),0))into v_metrics;
 select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'title',s.title,'starts_at',s.starts_at,'status',s.status)order by s.starts_at desc),'[]'::jsonb)into v_sessions from public.academy_sessions s where p_branch_id is null or s.branch_id=p_branch_id;
 return jsonb_build_object('metrics',v_metrics,'items',v_items,'sessions',v_sessions,'weighting','Each learner-class enrolment contributes one equally weighted progress value.','pagination',jsonb_build_object('page',v_page,'page_size',v_size,'total',v_total));
end$$;
revoke all on function public.churchmetric_academy_instructors_v1(uuid,uuid,text,text,integer,integer)from public,anon;
grant execute on function public.churchmetric_academy_instructors_v1(uuid,uuid,text,text,integer,integer)to authenticated;
