create or replace function public.churchmetric_department_detail_v1(p_department_id uuid,p_branch_id uuid default null,p_search text default '',p_page integer default 1,p_page_size integer default 25)
returns jsonb language plpgsql stable security invoker set search_path=public,pg_temp as $$
declare v_role text:=public.churchmetric_role();v_claim_branch uuid:=public.churchmetric_branch_id();v_branch uuid;v_search text:=lower(btrim(coalesce(p_search,'')));v_page integer:=greatest(1,coalesce(p_page,1));v_size integer:=least(100,greatest(1,coalesce(p_page_size,25)));v_department record;v_result jsonb;
begin
  if v_role not in ('admin','globaladmin') then raise exception 'Administrator access required' using errcode='42501';end if;
  if v_role='admin' then if p_branch_id is not null and p_branch_id is distinct from v_claim_branch then raise exception 'Cross-branch department access is forbidden' using errcode='42501';end if;v_branch:=v_claim_branch;else v_branch:=p_branch_id;end if;
  select d.id,d.name,d.description into v_department from public.departments d where d.id=p_department_id;if not found then raise exception 'Department not found' using errcode='P0002';end if;
  with scoped_members as materialized(select p.id,p.full_name,p.email,p.phone,p.membership_code,p.verified,p.created_at,p.date_joined,p.branch_id from public.profiles p where p.department_id=p_department_id and (v_branch is null or p.branch_id=v_branch)),filtered_members as materialized(select * from scoped_members m where v_search='' or lower(coalesce(m.full_name,'')||' '||coalesce(m.email,'')||' '||coalesce(m.phone,'')||' '||coalesce(m.membership_code,'')) like '%'||v_search||'%'),page_members as(select * from filtered_members order by lower(full_name),id limit v_size offset((v_page-1)*v_size)),scoped_leaders as materialized(select dl.leader_id id,dl.user_id,dl.user_full_name full_name,dl.user_email email,dl.title_name,dl.start_date,dl.end_date,dl.is_active,dl.branch_id from public.department_leadership_view dl where dl.department_id=p_department_id and (v_branch is null or dl.branch_id=v_branch)),scoped_attachments as materialized(select a.id,a.branch_id,a.file_name,a.mime_type,a.size_bytes,a.created_at from public.department_attachments a where a.department_id=p_department_id and (v_branch is null or a.branch_id=v_branch)),attendance_values as(select count(*)::numeric total,count(*) filter(where lower(coalesce(a.status,'')) in ('confirmed','present'))::numeric present from public.attendance a where a.department_id=p_department_id and (v_branch is null or a.branch_id=v_branch))
  select jsonb_build_object('department',jsonb_build_object('id',v_department.id,'name',v_department.name,'description',v_department.description),'branch_id',v_branch,'metrics',jsonb_build_object('total_members',(select count(*) from scoped_members),'active_members',(select count(*) from scoped_members where verified is true),'department_leaders',(select count(*) from scoped_leaders where is_active is true),'attendance_rate',(select case when total=0 then 0 else round(present/total*100,1) end from attendance_values)),'members_total',(select count(*) from filtered_members),'page',v_page,'page_size',v_size,'members',coalesce((select jsonb_agg(to_jsonb(m) order by lower(m.full_name),m.id) from page_members m),'[]'::jsonb),'leaders',coalesce((select jsonb_agg(to_jsonb(l) order by l.is_active desc,l.start_date desc nulls last,l.full_name) from scoped_leaders l),'[]'::jsonb),'attachments',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at desc) from scoped_attachments a),'[]'::jsonb)) into v_result;
  return v_result;
end $$;
revoke all on function public.churchmetric_department_detail_v1(uuid,uuid,text,integer,integer) from public,anon;
grant execute on function public.churchmetric_department_detail_v1(uuid,uuid,text,integer,integer) to authenticated;
comment on function public.churchmetric_department_detail_v1(uuid,uuid,text,integer,integer) is 'RLS-scoped department summary, paginated members, leaders, and attachment metadata. SECURITY INVOKER.';
