import 'package:flutter/material.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import '../../core/theme/app_theme.dart';
import '../../core/utils/wpcc_time.dart';
import '../../core/widgets/section_empty_state.dart';
import 'profile_repository.dart';

class ClassesPage extends StatefulWidget{const ClassesPage({super.key});@override State<ClassesPage> createState()=>_ClassesPageState();}
class _ClassesPageState extends State<ClassesPage>{final repo=ProfileRepository();late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=repo.classes();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Classes',style:TextStyle(fontSize:14,fontWeight:FontWeight.w500))),body:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return SectionEmptyState(icon:PhosphorIcons.warningCircle(),message:'Unable to load classes',height:220);final rows=s.data??const[];if(rows.isEmpty)return SectionEmptyState(icon:PhosphorIcons.graduationCap(),message:'No classes assigned',height:260);final completed=rows.where((e)=>e['status']=='completed').length;final progress=rows.where((e)=>e['status']=='in_progress').length;final due=rows.where((e)=>e['due_at']!=null&&e['status']!='completed').length;return ListView(padding:const EdgeInsets.fromLTRB(18,18,18,30),children:[Row(children:[Expanded(child:_metric('$completed','Completed')),Expanded(child:_metric('$progress','In progress')),Expanded(child:_metric('$due','Due'))]),const SizedBox(height:20),...rows.map(_course)]);}));
Widget _metric(String v,String l)=>Column(children:[Text(v,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w600)),const SizedBox(height:3),Text(l,style:Theme.of(context).textTheme.labelSmall?.copyWith(color:WpccColors.muted))]);
Widget _course(Map<String,dynamic> c){final due=DateTime.tryParse(c['due_at']?.toString()??'');final pct=(c['progress_percent'] as num?)?.toInt()??0;return Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:const Color(0xFFF1F2F6),borderRadius:BorderRadius.circular(14)),child:Icon(PhosphorIcons.bookOpen(),size:19)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(c['title']?.toString()??'Class',style:const TextStyle(fontSize:13,fontWeight:FontWeight.w500)),const SizedBox(height:4),Text(due==null?'$pct% complete':'$pct% · Due ${WpccTime.transactionDate(due.toIso8601String()).split(' · ').first}',style:Theme.of(context).textTheme.bodySmall?.copyWith(color:WpccColors.muted)),const SizedBox(height:7),LinearProgressIndicator(value:pct/100,minHeight:4,borderRadius:BorderRadius.circular(10),backgroundColor:const Color(0xFFF0F1F4),valueColor:const AlwaysStoppedAnimation(WpccColors.ink))]))]));}
}
