import 'dart:ui';
import 'package:flutter/material.dart';
import '../../app/theme/design_tokens.dart';
import '../../flutter_flow/custom_icons.dart';

class V76InitialsAvatar extends StatelessWidget { const V76InitialsAvatar({super.key, required this.initials, this.size = 44}); final String initials; final double size; @override Widget build(BuildContext context) => Container(width: size, height: size, alignment: Alignment.center, decoration: const BoxDecoration(shape: BoxShape.circle, gradient: LinearGradient(colors: [Color(0xFF9277F6), Color(0xFFE9B9FA)], begin: Alignment.topLeft, end: Alignment.bottomRight)), child: Text(initials, style: TextStyle(color: Colors.white, fontSize: size * .34, fontWeight: FontWeight.w600))); }
class V76FrostedHeader extends StatelessWidget { const V76FrostedHeader({super.key, required this.child, this.active = false}); final Widget child; final bool active; @override Widget build(BuildContext context) => ClipRect(child: BackdropFilter(filter: ImageFilter.blur(sigmaX: active ? 12 : 0, sigmaY: active ? 12 : 0), child: ColoredBox(color: context.tokens.background.withValues(alpha: active ? .8 : 1), child: child))); }
class V76ExpandableSearch extends StatefulWidget { const V76ExpandableSearch({super.key, required this.onChanged}); final ValueChanged<String> onChanged; @override State<V76ExpandableSearch> createState() => _V76ExpandableSearchState(); }
class _V76ExpandableSearchState extends State<V76ExpandableSearch> { final _controller = TextEditingController(); final _focus = FocusNode(); bool _open = false; @override void dispose() { _controller.dispose(); _focus.dispose(); super.dispose(); } @override Widget build(BuildContext context) => AnimatedContainer(duration: MediaQuery.of(context).disableAnimations ? Duration.zero : const Duration(milliseconds: 210), width: _open ? 190 : 40, height: 40, decoration: BoxDecoration(color: context.tokens.surface, borderRadius: BorderRadius.circular(20), border: Border.all(color: context.tokens.border)), child: _open ? TextField(controller: _controller, focusNode: _focus, onChanged: widget.onChanged, onEditingComplete: () { if (_controller.text.isEmpty) setState(() => _open = false); }, decoration: const InputDecoration(hintText: 'Search', border: InputBorder.none, contentPadding: EdgeInsets.symmetric(horizontal: 14))) : IconButton(icon: const Icon(FFIcons.kmagnifyingGlass), onPressed: () { setState(() => _open = true); _focus.requestFocus(); })); }
Future<T?> showV76BottomSheet<T>(BuildContext context, Widget child) => showModalBottomSheet<T>(context: context, backgroundColor: Colors.transparent, isScrollControlled: true, builder: (_) => ClipRRect(borderRadius: const BorderRadius.vertical(top: Radius.circular(32)), child: BackdropFilter(filter: ImageFilter.blur(sigmaX: 12, sigmaY: 12), child: ColoredBox(color: context.tokens.surface, child: child))));
